### ISSUE TITLE
Request: Summoner

### ISSUE THREAD

**Issue by Wolfies11681** [Nik-Potokar/XIVSlothCombo#1012]
I have pool under searing light enabled only so i know this isnt bug, but a suggestion. I was killing a boss and it died with finishing Bahamut with only 1 fester left..by the time we got to the end of the next trashpull i was spamming Phoenix; however, Phoenix didn't burn that one fester in order to cast energy drain and then SIT on the 2 festers until the next bahamut..is that possible to implement? or is it not worth it?

**Comment by Genesis-Nova** [comment]
Due to the way pooled festers works it only uses festers during searing light (your selected burst phase)
This is a very niche problem to have and in all my time playing smn I can't say I've actually had this happen to me. 
Best way I think would just to be to manually use that last fester/ed during a trash pool to set up phoenix to ED/ES to get back to two aethercharge stacks.
