### ISSUE TITLE
[SMN] What is the point of the Ruin III option?

### ISSUE THREAD

**Issue by Random-Stack-Random-Day** [Nik-Potokar/XIVSlothCombo#112]
I don't recognize it so I'm thinking it's new, what exactly is its use case? If it said Ruin II I would think maybe it was something for when Ruin II was instant, but it's for Ruin III which has always had a cast time.

**Comment by Iaotle** [comment]
It's for mobility.

**Comment by Random-Stack-Random-Day** [comment]
None of the Ruins are instant anymore, so I'm confused on what it does for mobility.

**Comment by Iaotle** [comment]
So? They still allow you to move lol... You play SMN?

**Comment by Iaotle** [comment]
Egis last for 30s. Except for Titan, they all have abilities that can be swiftcast.

Garuda Slipstream can be delayed by using Ruin III, or Swiftcast using the same method if you need to for any reason.
Ifrit Ruby Rite/Catastrophe can be delayed in order to wait for your Swiftcast to come off CD, and gives you the necessary weave slot to use it without interrupting your GCD.

Imagine you want to move during Ifrit phase. What is your solution? You can't wait for the 2.8s cast time,  but you probably can wait for the 1.5 (slidecast reduces this even further) second cast time of Ruin III. This loses you 0 damage unless you're in a party buff window (you shouldn't be since you have Bahamut every 2min), it just moves up your pre-demi Ruin III.

Without XIVCombo you would simply press R3 on your bar. With XIVCombo your Ruin III is replaced by your egi attack. Hence if you need R3 on your bar with the current setup it's impossible to have it while you have egi summoned. This feature allows you to have a nice and convenient button save setup while still allowing to have R3 cast. 
I've used it in Savage and it works great.

**Comment by Random-Stack-Random-Day** [comment]
Ahhh, makes sense, esp in regards to saving Egi abilities. Thanks for the second reply, it was more useful than the condescending one.

**Comment by Iaotle** [comment]
It's just obvious why you need it if you've played SMN on high level. Guess it's not as obvious as I'd thought.
