### ISSUE TITLE
[Healers] Request: Healer DPS DoT Feature on ToT, Cure II on Freecure Proc

### ISSUE THREAD

**Issue by Ivylia** [Nik-Potokar/XIVSlothCombo#113]
If possible, an option for the various healer DPS Features utilizing damage over time spells [Aero, Combust, Bio, etc] to take into account the Target of Target's DoT status (for applying/reapplying before is wears off) would be amazing as it would allow the Tank/Heal target to stay targeted while allowing the DPS Feature to function smoothly. As it stands the DPS Feature will repeat the DoT spell. If this isn't possible, a simple timer version (rather than checking for the debuff on the target) where the DoT spell becomes available in the DPS feature after a certain amount of time has passed would be wonderful, too.
Another request would be for Cure I to switch to Cure II when the trait Freecure procs.
Thank you for all the time and effort you have put into this, it is much appreciated.

**Comment by Iaotle** [comment]
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation **please stop typing walls of text like this** ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

Cure feature is useless because freecure is useless and should never be used.

Make every request a separate issue.

What you really want in regards to targeting is mouseover healing. Use [ReAction](https://github.com/UnknownX7/ReAction).

**Comment by Codemned** [comment]
You should be nicer Iaotle.
