### ISSUE TITLE
[WAR] Add Bloodwhetting on CD

### ISSUE THREAD

**Issue by ladyredxiv** [Nik-Potokar/XIVSlothCombo#1135]
So, I know this (might) be a bit of a niche thing, since Bloodwhetting also shares a cooldown with Nascent Flash, but do you think it might be possible to add this into the standard rotation as an option? Would be kind of nice to just be able to naturally use it on CD.

Edit: As a checkbox feature, not necessarily in like... A simple rotation. If that makes sense.

**Comment by Spanglish1337** [comment]
Could you expand in why you would want to use it on cooldown, since it is a defensive spell and not an offensive one?

Otherwise the devs might not even consider adding it, because as far as I understand, the big usage is if you are being targeted with a tankbuster or if you need to heal yourself up quickly in aoe packs.

If you use it blindly when it's on CD, you might use valuable usage of it. If you expand on the reasons of it, the better!

**Comment by ladyredxiv** [comment]
Of course! So, like I mentioned, it might be a bit of a niche thing since I personally tend to use it as a defensive weave, especially when I'm spamming the AoE multi-button for trash packs and the like. In single target, I defs use it for a TB or something like that.

Thinking on how abilities like Second Wind and such are currently able to be fixed up with a slider for when it will trigger, I feel like that's where my thinking is versus flat on CD. (You've got a point there, thank you!)
