### ISSUE TITLE
[BRD] Simple mode does not offer oGCDs when all cooldowns 0

### ISSUE THREAD

**Issue by NikaLeets** [Nik-Potokar/XIVSlothCombo#1220]
The best way to reproduce this is to try to use simple mode with song option in Palace of the Dead floors 51-60. What seems to happen is when no song is playing and all oGCDs don’t have cooldowns running (they are ready wilt full charges) simple mode will occasionally stop offering oGCD replacements for Heavy Shot

manually firing oGCDs seem to get it unstuck. In deep dungeons, this can happen if there is downtime traveling and multiple abilities come off cooldown.

**Comment by SirDK** [comment]
Confirm. Bug still happens. Or there is another reason for it perhaps. Not when all cooldowns 0. Sometimes during single target simple rotation there are no oGCD and charges being wasted. But then rotation suggests raging strikes and oGCD appear again. It looks like charges being saved for burst window or smth. But they are also being wasted before raging strikes because they are maxed out. oGCD appear in AOE simple rotation when they must in single, their AOE variations.
