### ISSUE TITLE
[SGE] Request: Option to not turn Docis into Eukrasia when the target's hp % is low

### ISSUE THREAD

**Issue by Terroosh** [Nik-Potokar/XIVSlothCombo#129]
Hi, I was wonder if an option could be provided from the title. A lot of times when mobs/bosses are near death SGE dot will fall off causing the next attack to be a Eukrasian Docsis which will have no benefit.

**Comment by Nik-Potokar** [comment]
That's something im testing no ETA tho

But what i can do for you now is ether swap/give another option for the dot(so that you can still use Dosis/Malefic/Broil/glare manually)

**Comment by Terroosh** [comment]
> ether swap/give another option

I have it on Eukrasia for now, hopefully your testing goes well ^^

**Comment by rushtothesun** [comment]
> That's something im testing no ETA tho
> 
> But what i can do for you now is ether swap/give another option for the dot(so that you can still use Dosis/Malefic/Broil/glare manually)

I'm using 

` && ((EnemyHealthPercentage() >= 10 && EnemyHealthMaxHp() < 550000)|| (EnemyHealthMaxHp() >= 600000 && EnemyHealthPercentage() >= 1)))`

At the end of line 124 in SGE.cs but this will only work for endgame. 

In Smiletron the adds health ranged from  224K to 448K. Boss 1 & 2 had 2M health and Boss 3 had 3M.  So the first part of the code says if it's an add (<550k HP) then stop dotting at <10% HP. The second part is if it's a boss (>600k HP) then stop dotting at <1%. I haven't really decided what % the boss should be at.

  You could further distinct dungeon bosses from trials/raids but it's going to make the line really long.  And because of the different HP values for lower level dungeons, adding a level sync support is just too time consuming.

**Comment by Iaotle** [comment]
The real cool way to do this would be to grab all the boss names and put them in a big database :P

**Comment by Nik-Potokar** [comment]
Added optional  feature that lets you check for stuff like current boss Hp, max Hp and % Hp. 
I only did some tests on the dummy and on P3S with darkfire since you dont wanna DoT those and had no issues so far. 
Also all of these values currently are shared with AST (Can be separated later on)

**Comment by Terroosh** [comment]
Works great
