### ISSUE TITLE
[PLD] Atonement before 1-2-3

### ISSUE THREAD

**Issue by Tykku** [Nik-Potokar/XIVSlothCombo#1295]
I would like to see an option to use Atonement before any 1-2-3 combo, taking priority over all. Or at least have a toggle for this option.
I understand the change where atonement no longer breaks combo so this isn't required outside of the burst window. But this is very required in the burst window.

Atonement deals 400 potency
Fast Blade is 200
Riot Blade is 300
Following the standard opener from The Balance (https://xiv.sleepyshiba.com/pld/img/64-v1.png) leaves the last 2 GCD's of the opener as Fast Blade/Riot Blade under the current settings resulting in a 60 potency lost (20% of 300) in the opener alone. This is compounded throughout an encounter.

Thanks!

**Comment by Taurenkey** [comment]
Hi, the image you linked is exactly how Sloth does the filler, as Royal Authority is the last hit of the 1-2-3 combo, so all stacks are spent just before they're earned again.

However I will add an option to spend them before restarting the basic combo.

**Comment by Tykku** [comment]
The filler portion isn't the issue, it's what sloth does inside Flight or Flight. Which right now is prioritizes lower GCD attacks inside a 20% dmg buff. Sloth right now has the last 2 GCDs in the opening FoF as Fast Blade/Riot Blade, when it should be Atonement/Atonement. It does this because it doesn't spend atonement until it absolutely has to.

Thank you for adding the option.

**Comment by Taurenkey** [comment]
I've been playing about quite a bit and I think with base skill speed, you're gonna get drift somewhere no matter what since the priority is FoF on cooldown. Once you're out of the FoF buff, you get 16 GCDs to spend before it's back up, with the filler rotation being 7 GCDs per rotation (1-2-3, 3x Atonement, 1x Holy Spirit), which naturally doesn't divide nicely into 16. There has to be a sacrifice somewhere, since trying to tick all of the infographic boxes is a mathematical nightmare.

Keep FoF on cooldown ✔
Follow Filler ✔
Perfect Burst everytime ❌

Keep FoF on cooldown ❌
Follow Filler ✔
Perfect Burst everytime ✔

Keep FoF on cooldown ✔
Follow Filler ❌
Perfect Burst everytime ✔
