### ISSUE TITLE
Samu, Reaper, Monk Bug?

### ISSUE THREAD

**Issue by Nouhime** [Nik-Potokar/XIVSlothCombo#1347]
Hello,
I've been having problems with the plugin and three classes since patch 6.55.
Both are with Samu, Reaper and Monk.

With Samu I have problems with the following skills.

- Meikyo Shisui
- Hissatsu: Shinten
- Hissatsu: Senei
I no longer get this activated automatically in the rotation. Even if I do this separately in the hotbar, I can still sometimes no longer get it activated using a button.

True North > Savage Blade?
In the three classes mentioned above I have problems with the skill **True North**, after the first activation in a rotation it suddenly wants to use the skill **Savage Blade** (this no longer exists and this was a PLD skill), after a few seconds I can then Second time using **True North** again.

**Comment by Kagekazu** [comment]
Hey! 

can u do /scombo debug SAM and send the file? then i can use your settings and test if i have any issues/what might be wrong.

For the True North, it is intentional, its an option u got enabled called True North Protection.

![image](https://github.com/Nik-Potokar/XIVSlothCombo/assets/95875972/06afd1bb-0e97-42cb-8f06-73516f49dd6d)

it stops u from using True North while its already active. If u dont want that protection, u can disable that option and then it won't change to Savage Blade.

**Comment by CaithSith** [comment]
Back after a break and I'm having the same issue. Does not use Meikyo Shisui/True North/Ikishoten/ANY Kenki spenders in the combo chain. Debug is saying I don't have a cap set, but it's active and set to 70. As for Meikyo, Ikishoten, and TN, I haven't a clue. Hope this helps.
[SlothDebug.txt](https://github.com/Nik-Potokar/XIVSlothCombo/files/14739214/SlothDebug.txt)
