### ISSUE TITLE
AST / DRG questions

### ISSUE THREAD

**Issue by Clueless-AI** [Nik-Potokar/XIVSlothCombo#1375]
Hello, 
Recently I noticed that my AST cards are always hard locked to the target that Sloth picks and even if I mouseover someone it still goes in the other one picked by the plugin, is there a way to fix this ? (It used to override all the time but its no longer the case)

For DRG, I was wondering if there's a similar system as AST where it picks a target for you instead of you having to mouseover still.

Thanks in advance

**Comment by Kagekazu** [comment]
for AST, what option do u use for the cards?
![image](https://github.com/Nik-Potokar/XIVSlothCombo/assets/95875972/4d258df6-69b6-4752-a2a2-172fc8e96b0b)
afaik this option still prioritizes ur MO target ( id have to doublecheck when im playing AST tho xD )

for DRG, there is the option of using ReAction to make a stack for eye, where it automatically use it on the target in the stack.
This is the stack i use, where it has prio as if u mousover someone it takes prio, otherwise it uses the balance list.
![image](https://github.com/Nik-Potokar/XIVSlothCombo/assets/95875972/f50629cb-8b5b-4336-b056-20e03639ba19)

**Comment by Ashe-H** [comment]
Hello,
Sorry for the long wait, been away for quiet some time. 
For Astro I'm using the same settings as you and sometimes even if I'm mouseovering someone the card goes onto someone else it doesn't happen all the time but quiet often.
For DRG you ReAction is interesting I've never used ReAction before but looks like Dragon Sight is going away in DRG so dunno if its worth trying it or not.
Thanks a lot

**Comment by Kagekazu** [comment]
i would recommend to wait until after DawnTrail then, since we arent updating anything until after the launch. Might be easier to see with the changes for what is needed and what can be skipped :D

**Comment by Tartarga** [comment]
Cards redone by SQ. Obsolete with Dawntrail
