### ISSUE TITLE
[PLD] using intervene cancels out the new goring blade

### ISSUE THREAD

**Issue by LordLackusX** [Nik-Potokar/XIVSlothCombo#1454]
as described, done the new extreme and noticed that a couple of times my goring blade did not go off during a burst window, I went to a dummy and found out that using intervention and possibly something else  cancels out the cast shown on the button that  replaces fast blade and moves to a next  step

**Comment by Akechi-kun** [comment]
What’s happening is that in the code, it’s only checking to see if the last ability used was Blade of Honor. Due to BoH being an oGCD, anything after Both can mess this up, including Intervene, Spirits Within, or really any oGCD for that matter including mit. I added some checks to ensure the use of Goring Blade at all levels. See #1433 for more details.

fixed in next update

**Comment by LordLackusX** [comment]
Thank you very much, I am sure you are working on this already but just in case, it would be great if you could add early spend option for goring blade, thank you.

**Comment by Akechi-kun** [comment]
At the moment I am not the main guy working on PLD, I just fixed the Goring Blade issues 🫡 but if you want to submit this as a suggestion, open another issue and feel free

**Comment by Akechi-kun** [comment]
This issue has been fixed in the newest update. Please update & close :)
