### ISSUE TITLE
[DRG] Weapon skills not usable when synced to low level

### ISSUE THREAD

**Issue by qnesp1987** [Nik-Potokar/XIVSlothCombo#1455]
Was doing roulettes and in low level dungeons/guildhests true thrust goes off, but then the button converts to the upgraded high level weapon skill and cnanot be pressed. Had to turn off sloth so i can hit the enemies.

**Comment by Kagekazu** [comment]
How are u using sloth when drg is not released for DT yet?

**Comment by Akechi-kun** [comment]
DRG is disabled right now, so I assume you cloned & re-enabled it.

DRG is disabled because it’s hasn’t been updated for Dawntrail. It’s the reason why the jobs that are disabled, are disabled in the first place. Double check your repo & If you’re using an old build (which I doubt) please update and the UI will show as DRG currently being unable for use. We also politely ask to NOT report any issues unless they are directly from the plugin, or `main`
