### ISSUE TITLE
[GNB]Issue GNB_ST_MainCombo 

### ISSUE THREAD

**Issue by BungzeroQ** [Nik-Potokar/XIVSlothCombo#1526]
I would like to rollback GNB_ST_MainCombo settings that include the Sks settings or revert to the original source code. Normally, I use Sks <= 2.45. After syncing the fork and testing, GNB_ST_MainCombo does not work as well as before and performs much worse.

**Comment by Akechi-kun** [comment]
99.9% not happening. I'm updating the rotation for current gameplay, and since we're Lv100 & the meta for GNB has been 2.5 over 2.4 since 6.2 (Lv90 btw), we found it best to make the swap to only 2.5. The only reason you would play 2.4x GNB is to do old content like Ultimates (which we do NOT recommend this plugin for btw).. and even if so, the damage performed is still more than enough to get the clear on any old content at the very least.

If you do not like it, then we do apologize for the inconvenience, and there are (probably) other plugins out there that support 2.4, however the decision is final unless you can convince our main dev otherwise _(good luck)._

**Comment by Tartarga** [comment]
🧵
