### ISSUE TITLE
[BLU] Some additional combos

### ISSUE THREAD

**Issue by PapaSteel** [Nik-Potokar/XIVSlothCombo#162]
Now that blue mage is actually on the list, I have no idea who'd benefit from this but I thought I'd list the standard 1-2 or 1-2-3 combos just for the sake of absolute completion. I don't actually expect anyone to do this, I just think it's neat to point out that the list is actually very manageable if someone was bored.

Swiftcast -> Angel Whisper  _(Raise Combo)_
Level 5 Petrify -> Whistle -> Drill Cannons   _(Petrify Combo)_
Veil of the Whorl -> Ice Spikes   _(Counterattack Feature)_
Swiftcast if available -> The Ram's Voice -> Ultravibration   _(Deep Freeze combo)_
Devour -> Off-Guard -> Magic Hammer -> Lucid Dreaming, as priority system   _(Sustain Feature)_
Bad Breath -> Addle, as priority system   _(Debuff Combo)_
Feather Rain -> Shock Strike -> The Rose of Destruction -> Glass Dance, as priority system   _(Primal Combo)_
White Knight's Tour -> Black Knight's Tour   _(Bind Combo)_
Peripheral Synthesis -> Mustard Bomb  _(Lightheaded Feature)_

Fellow BLUs, did I miss any?

**Comment by Iaotle** [comment]
@damolitionn this has your name on it, also can you use some \n characters in your descriptions because I have to drag the window out to half my screen to read the required spells list for moon flute.

**Comment by damolitionn** [comment]
I see, my monitor's large enough to not have that issue so I didn't really pay attention to formatting but sure.

I'll add those combos some time this week, but you can't bristle Nightbloom. It's an ability not a spell.

**Comment by PapaSteel** [comment]
My fault on that one. That was a reddit suggestion that I didn't vet.

**Comment by Iaotle** [comment]
@damolitionn so is mine but I prefer not having to move it to other monitor to read the description or to make the window super huge :P

**Comment by Iaotle** [comment]
@damolitionn is this done or are you not gonna do it?

**Comment by damolitionn** [comment]
@Iaotle Be my guest. Life got busy for me, I also took a break to focus on other things. I mean at the end of the day you volunteered this on me and I was being nice and took a look at it but I don't really owe you anything. I took a look at the logic of some of it, but because some of these requests relate to spells that don't rely on putting buffs/debuffs or have a CD, it'll require you to add step variables to distinguish when a spell is cast and that's where I stopped because like I said stuff got in the way. Anyway, feel free to do it because I guess I'm "not gonna do it".

**Comment by damolitionn** [comment]
Added features.

Didn't add the petrify combo seeing as Level 5 Petrify has a low chance of success and who's really going to waste GCDs on trash to proc Level 5 Petrify when there's all the other spells that do the job better.

Counterattack Feature wasn't added because Veil of the Whorl isn't worth taking over Glass Dance, in niche situations it would work out if for some reason the damage pattern is exactly every 90 seconds which is unlikely so you'd end up drifting Veil or not proccing it.

Sustain Feature has Magic Hammer removed because intuitively it seems more like a Tank Debuff feature of keeping up Bad Breath, Devour, Off-Guard.

Debuff Feature is now Magic Hammer and Addle and not Bad Breath because they do the same thing.

Primal Combo also includes J Kick.

**Comment by PapaSteel** [comment]
Whoa. You're amazing.
