### ISSUE TITLE
[PLD] Confetior/Blades combo issues

### ISSUE THREAD

**Issue by Sissyhime** [Nik-Potokar/XIVSlothCombo#1634]
It seems like the Confiteor/Blades combo on the main button sometimes doesn't work, making for inconsistent combos. Looks to be because FoF is required for them to proc, but that is not specified in the options. 

On a similar note, to be honest, it feels restricting to have so many skills "prefer" to be used after other things when I'd rather pool them for bosses. It breaks consistency in combo chains, where I drop timers and buffs between pulls because it demands I expend a full combo chain right before a boss pull when I just wanted to use goring blade. I like opening on bosses with full burst combos, so using full requiescat combos just to use goring blade, or requiring FoF to have the Conf/Blades combo appear on my main button seems a little silly as a "preference" or requirement. Just minour critique, don't wanna come off as too nitpicky.

**Comment by Kaeris-Tempest** [comment]
> It seems like the Confiteor/Blades combo on the main button sometimes doesn't work, making for inconsistent combos. Looks to be because FoF is required for them to proc, but that is not specified in the options.

The Confiteor combo is working as intended. FoF and Requiescat both have the same cooldown (60s) and should **always** be used together; there is no situation you'd want to "just use Goring Blade" because now your two major cooldowns are misaligned.

Confiteor can only be used after Requiescat. Requiescat is only used after FoF. It's all noted in the toggles.

> it feels restricting to have so many skills "prefer" to be used after other things

A priority system is necessary for smart cooldown usage, for every job. You cannot simply use every cooldown as soon as they become available. Certain things need to be used after others, or sometimes they cannot based on level. There is a lot of thinking involved.

> I'd rather pool them for bosses.

This is not something we offer support for in Sloth. If you want to "pool" your cooldowns, simply don't spam the combo. If you don't give Sloth the opportunity to weave FoF or Requiescat, it won't use them.
