### ISSUE TITLE
[AST] Automatically Apply All Cards

### ISSUE THREAD

**Issue by rceglie** [Nik-Potokar/XIVSlothCombo#1635]
I know there's already a feature to automatically apply the two dps cards to dps based on the priority. Would it be possible to do something similar with the mit/healing cards (Arrow, Bole, Spire, Ewer) on Play II and III, like automatically give them to the person who is top aggro on the mob you're targeting, or just the first tank in your party list?

**Comment by edewen** [comment]
Typically not allowed to do none dps things like that. But i did just add bole/arrow to the st heals button. hit me on the discord i can show you my reaction setup to do something good enough.

**Comment by Taurenkey** [comment]
Generally we tend to avoid putting these sort of buff abilities onto the healing features just because they don't provide an immediate benefit when you might be needing an actual heal/shield. I say generally because exceptions have been made before depending on the job and action (such as WHM Thin Air).

Healing actions will never be automatically targetted, the DPS cards are a sort of one-off kind of feature just due to the nature of how it works, that's why other jobs won't see automatic targetting on their features until SE introduce something as a major part of their kit that needs to be managed all the time and not just every 2 mins.
