### ISSUE TITLE
[GNB] Request: Separate some features from Advanced Combo

### ISSUE THREAD

**Issue by t-l13** [Nik-Potokar/XIVSlothCombo#1684]
As I've maintained in other issues I've opened, I mostly use this plugin akin to XIVCombo, for paging basic combos. I tend to not use the features that involve doing the rotation for you.

Currently, it appears that if I check only the Advanced Combo options for GNB, their main combo will page into Gnashing Fang after I push the Gnashing Fang button (what for? I already have to have a dedicated button to initiate it.) It also says something about subbing Burst Strike to prevent overcapping of resources.

I would like to disable these features. That appears impossible because they are not separate settings. I play RPR and DRK besides, and their "Advanced combo" options do not include extra features unless you toggle them on. I would like for Gunbreaker's settings to be congruent with these classes so that the way I am attempting to use the mod is supported.

Thank you.

**Comment by Akechi-kun** [comment]
> I mostly use this plugin akin to XIVCombo, for paging basic combos.

I really hope you're not using _both_ of these plugins at the same time, because regardless of settings it's not recommended at all and can cause issues with your gameplay.

If you just enable the option "_Advanced Gunbreaker Feature_" and nothing else, it _should_ just do 1-2-3 and _Burst Strike_ only.

> It also says something about subbing Burst Strike to prevent overcapping of resources.

If you have 3 carts and your last combo action was _Brutal Shell_, it will send _Burst Strike_ to ensure you do not waste a cartridge by overcapping, regardless of settings. You never want to overcap in any situation.

I just reworked GNB recently so it's to be expected there are some bugs. However, #1600 is my current PR with the latest updates & fixes. If you'd like to pull that and see if the issue is still happening, feel free. Also make sure you have all the other options unticked/disabled except Advanced Gunbreaker Feature when testing this again & a screenshot of your settings is always helpful as well so I can ensure no other options are conflicting.
