### ISSUE TITLE
feature requests + bug

### ISSUE THREAD

**Issue by hhharkness** [Nik-Potokar/XIVSlothCombo#1838]
bug: if the standard dance opener option is checked under dancer advanced - standard dance option, it shows up even with the standard dance option unchecked

feature requests:
1. first of all, some sort of info on exactly which actions are added and in what order to options that add multiple things would be great, ideally in the info hover but at the very least on a wiki somewhere. especially necessary when being new to a job and not knowing all the actions yet, and sometimes the existing descriptors don't do exactly what's expected. if possible an option to customise the order would also be great
2. for physical ranged, having head graze on foot graze when available is great but why not also add leg graze and alternate them like the dots on iron jaws feature

for tanks

3. interject option for advanced mode (like the one with head graze for physical ranged)
4. rampart and reprisal on one button - would include double reprisal protection*

*which currently says replaces with stone, does that mean the white mage spell? if so i'm curious as to why

for dancer:

5. on advanced mode, options to add starfall dance and finishing move, and remove fan dance
6. an option to have fan dance 3&4 on 1&2 when available
7. have tech step on standard step when available
8. an option like the bard buffs one, with devilment+shield samba+flourish

for bard:

9. troubadour and the warden's paean in the bard buffs option

for reaper:

10. adding harpe on hell's in+egress for the free proc

for viper:

11. option to remove twinfang+twinblood from advanced modes

**Comment by zbee** [comment]
Thank you for your suggestions! I will just mention briefly that when so much is piled into a single issue it does make it more difficult for developers to actually take action with - it's usually worth breaking up into individual issues.
(e.g., if I made PR to implement the dancer options then it would try to close the whole issue not just that part of it)

That said, 

Could you please clarify this bug further in its own issue? Preferably with any picture you can provide of what you mean, as well.

1. Of course we do strive for better documentation, for clearer info while trying to keep things brief, and are pleased many people use Sloth to learn parts of jobs: I would say that does seem like a lot to basically provide what Simple Mode + The Balance provide, especially when we aren't necessarily intending to be a learning tool.

    - A customizable order would be neat, just not a change it's easy to fit in or even prioritize especially when it conflicts with something else we like: the option #s being consistent. This may well be a flat "no", but could be an option we consider when next we toy with the UI, especially if it sticks around as a UI suggestion in its own issue.

1. While there are many cases where Leg/Foot Graze may *look* like Debuffs you want to always apply when you can, they're really not. Interrupts like Head Graze have very clear uses, and a reliable benefit, but it's not so easy to know whether an enemy is immune to Leg/Foot Graze or not, so much of the time their casts are pointless.

1. Interject on tank Advanced Modes: A solid idea, though possibly outside of what we want to keep in tanks' main combos. May investigate and try to include this in my DRK changes.

1. Rampart+Reprisal: Mitigations are not currently something we generally combo in Sloth, so this won't be done, but it is under consideration.

    - As for why WHM's Stone: the point of the feature is to prevent you from using Reprisal, and we wanted to stay away from the ability not changing and not working or being greyed out or something. You definitely can't cast another job's ability, plus it's a very distinct change, so we felt it worked at every level.

1. +Star +Fan: Sure, I can look to include this in my DNC changes; especially if you make an issue requesting it more specifically.

    - As for making Finishing Move an option: No, it's almost exactly in line with an ability upgrade, it won't receive an option.

1. Fan3/4 on 1/2: I could add this to an eventual todo especially if you put together a new issue requesting it specifically, especially if you could expand on your use-case for this.

1. I may be mistaken, but this seems familiar like it already exists. Either way, similar to above: I could add this to a todo especially if you made a separate issue for it.

1. DNC Buffs Combo: This is something I would want to discuss more on its own issue, but it's probably a "no" on the surface; Devilment and Flourish have fairly specific timings you want to hit, and they're fast oGCDs, so I don't think it would be worth the effort.

1. Similar to Item 4 above: Mitigations are not currently something we generally combo especially into otherwise-DPS options in Sloth, so this won't be done, but it is under consideration.

And as for the Reaper and Viper, I am not familiar with those classes, so I have no comment on them other than: those who are familiar with them are much more likely to work with your ideas if they are in individual issues.

> [!NOTE]
> If you would like to discuss any of these further, please feel free to reference this message in a new issue specific to each request - Bullet point replies very quickly become very difficult to read and to follow.

**Comment by Kagekazu** [comment]
> for reaper:
> 
> 10. adding harpe on hell's in+egress for the free proc
Should be possible to add in my PR that i got for RPR.

> for viper:
> 
> 11. option to remove twinfang+twinblood from advanced modes
Doesnt that option already exist?
And if it doesnt, can u give me an example of why u dont want those 2 on the advanced mode?

I know i made seperate options for Uncoiled - Twins and Vicewinder - Twins

![image](https://github.com/user-attachments/assets/6385d063-b470-4299-8d1a-602cf52658fb)
![image](https://github.com/user-attachments/assets/4581b794-faf9-4b53-8efc-b0ed4f2929f6)


But i dont see the need of removing twinfang and twinblood off the main combo, since u have to use em or u lose the stacks anyway.

But im open to adding it if i get a good reason for it.

**Comment by hhharkness** [comment]
ah sorry, i will keep the separate issues thing in mind in the future! i only use git as a consumer so not that familiar with how it works (:
