### ISSUE TITLE
SAM Overcap AoE abilities

### ISSUE THREAD

**Issue by NikkoToska** [Nik-Potokar/XIVSlothCombo#214]
Just like the current SimpleSamurai Overcap, replace Fuga/Fuko with Kyuten and Guren.  These are the AoE equivalents to Kaiten and Shinten.  However, since they are higher levels, it would be good to replace Fuga/Fuko with Kaiten when below level 64 and Shinten when below level 70.

Another option to add for SAM, when you're in combat, ikishoten is off cooldown and your kenki is below 50, have it replace a rotation (single target or AoE) weaponskill.  And if ikishoten is off cooldown and your kenki is above 50, change the overcap number to 50 so you can  use it as quickly as possible.

One thing I still use on SAM from the Custom Combo plugin is the Iaijutsu to Tsubame, since it only switches after an Iaijutsu is used.  I like having the visual indicator on the icon before I use the ability.  Could you add an option like this?

And finally, while there is a Kaiten feature to change Iaijutsu into Kaiten, could you add one that changes Kaiten to Iaijutsu while the buff is active and then Tsubame after you use an Iaijutsu?  You could still use it for other abilities, but it would prevent accidental overuse.  So: Kaiten >(on use/while buff is active)> Iaijutsu >(on use)> Tsubame >(on use/skip if on cooldown of more than 3 seconds)> Kaiten

And finally!  I'm lv89 so I haven't tested it yet, but does the Ikishoten Namikiri Feature include Kaiten after Ikishoten?  Ogi is a weaponskill so it should work, and you should have kenki to make it work.  

Thanks!

**Comment by pynom** [comment]
One thing I still use on SAM from the Custom Combo plugin is the Iaijutsu to Tsubame, since it only switches after an Iaijutsu is used. I like having the visual indicator on the icon before I use the ability. Could you add an option like this?

I don't really understand this? Tsubame stacks are only shown as long as there is no valid Iaijutsu move to use

And finally, while there is a Kaiten feature to change Iaijutsu into Kaiten, could you add one that changes Kaiten to Iaijutsu while the buff is active and then Tsubame after you use an Iaijutsu? You could still use it for other abilities, but it would prevent accidental overuse. So: Kaiten >(on use/while buff is active)> Iaijutsu >(on use)> Tsubame >(on use/skip if on cooldown of more than 3 seconds)> Kaiten

This already exists, Kaiten is used before Iaijutsu and afterwards there is tsubame.

And finally! I'm lv89 so I haven't tested it yet, but does the Ikishoten Namikiri Feature include Kaiten after Ikishoten? Ogi is a weaponskill so it should work, and you should have kenki to make it work.

You neither Kaiten on Kaeshi Namikiri nor on Tsubame

**Comment by NikkoToska** [comment]
I've been working on all jobs so it's taking me a minute to remember why I was saying these things.

The first point was the conditions that tsubame appears.  In the /pcombo option, it appears only after iaijutsu is used, the the button starts as iaijutsu and changes to tsubame only when it's used.  Looking at it now, _please ignore me on this one_.  How it's implemented is fine, so no need to change.  But, looking at the descriptions again, I think they're switched.  'Iaijutsu to Tsubame-gaeshi' currently says when the sen **is not** empty, but it should say when it **is** empty.  And 'Tsubame-gaeshi to Iaijutsu' should say when sen is not empty.

On the Kaiten point, it's about iaijutsu changing to kaiten using the different kaiten features.  I was trying to ask for kaiten to change to iaijutsu.  The reason was that when you change iaijutsu to kaiten and you have 1 or more sen, the icon only shows kaiten and not which iaijutsu you're going to use.  The end result is the same, just like 'Iaijutsu to Tsubame-gaeshi' and 'Tsubame-gaeshi to Iaijutsu' has the same result, but the difference is that I can leave iaijutsu somewhere on my HUD to indicate the ability that's ready and have kaiten being the button that changes.

And the last point...  I'm not sure if the text changed or I just never noticed, but works great and the options are clear.  Sorry if it was my mistake! 

And thanks for listening to requests!
