### ISSUE TITLE
[MNK][AST][SCH][WHM] - things not working

### ISSUE THREAD

**Issue by doh666** [Nik-Potokar/XIVSlothCombo#218]
[ast] #7 dps feature (on malefic ) does not add combust on malefic 1 to fell
[sch] #188 fairy feature changes every action to summon Eos or Selene instead of those that requires a fairy
#190 Dps feature buff option only works it you have set broil 1 to 4 if you set ruin 1 the let it upgrade dose not work
[whm] #228 solace into misery changes every skill into misery instead of just solace
 #229 rapture into misery changes every skill into misery instead of just rapture 
[idea] could put misery on assize since both are aoe damage
[mnk] #90 monk basic rotation dose not work with #96 & 95 when used only does elixir field

**Comment by Nik-Potokar** [comment]
AST:
Seems to be working as intended. Can you provide bit more detail?
SCH:
Ruin1 Still works but dosent update the icon correctly (Mostly due to ruin2) but ill investigate.
Fairy Feature fixed so it should apply only to skills that need eos
WHM:
Fixing it rn
MNK:
#96 only replaces Masterful blitz with the combos. if you enable 95 and 97 those combos will be on main combo.
90# does not work with #96 because they are same features but 96 has more stuff on it

**Comment by Wyny01** [comment]
For the AST it seems the DPS feature(on malefic) are not working

**Comment by Nik-Potokar** [comment]
Should be all good now
