### ISSUE TITLE
[BLM] Thundercloud not triggering on AoE combo / Foul addition to AoE

### ISSUE THREAD

**Issue by LemonWaffles** [Nik-Potokar/XIVSlothCombo#231]
Yes, the AoE combo is a work in progress, still, worth reporting the issue.

Upon receiving the Thundercloud buff, the rotation just continues instead of switching to Thunder4/Thunder2. 

I tried comparing the proc code with the firestarter one, as it should be similar. Firestarter looks for a firestarter buff `CustomCombo.HasEffect(BLM.Buffs.Firestarter)`

So i added a `|| CustomCombo.HasEffect(BLM.Buffs.Thundercloud)` at the end of all thunder4/2 conditions (line 299) and it seems to work tho it's not quite instant.

For example:
Thunder 4 -> Sharpcast (just to test the proc system) -> And now it should go into another Thunder 4, instead it first goes to Fire 2 then to Thunder 4.

____________

Tried adding Foul to the AoE combo whenever it's available but i clearly don't know what i'm doing and failed miserably.

**Comment by Multidayz** [comment]
To jump onto this comment, I've been testing out Black Mage and currently only lvl 60, the Fire IV works beautifully but it's still missing functionality that maybe starts working at a later timeframe?
Example above is Thunder, on either my single target or aoe rotation the character never attempts to cast Thunder. If I apply it manually it also doesn't appear to refresh it or use it for procs. Was wondering if it's just a level thing and it kicks in later on.

Additionally does the rotation weave in Flare? I've never seen it cast without manually using it.

**Comment by Nik-Potokar** [comment]
> For example: Thunder 4 -> Sharpcast (just to test the proc system) -> And now it should go into another Thunder 4, instead it first goes to Fire 2 then to Thunder 4.
> 
> Tried adding Foul to the AoE combo whenever it's available but i clearly don't know what i'm doing and failed miserably.

The way it currently works
Sharpcast(Manual)>Blizzard2/HB2>Freeze>Checks if target has thunder debuff2/4 if no it does thunder if yes >Fire2/HF2(Until 7k mana or less)>Flare until mana is empty>if mana empty do B2/HB2>>>Repeat

So to answer the question it dosent care if you have thundercloud buff for not since if your target has the debuff it will continue to do F2/HF2 and if not then it will use thunder and if you happen to have thundercloud buff the cast will just be instant instead.

Also il see into adding foul into combo.

**Comment by Nik-Potokar** [comment]
@Multidayz So currently it only refreshes the dot when its about to expire if you have thundercloud buff and as mentioned above it uses flare when you are below 7k mana.
Oh and since i see that i forgot to update the tooltip description this whole aoe combo is on FLARE not on HB2 which is probably the issue here.

**Comment by Multidayz** [comment]
@Nik-Potokar Awesome thank you! That's fixes that! For Thunder to work for single target, do I need to initially cast it manually to get the ball rolling? or is that an option it could be doing like the other jobs like DoT on Glare3

**Comment by Nik-Potokar** [comment]
@Multidayz So for now you have to manually cast thunder and then it will refresh its self as long as you got a thundercloud buff on you.
It can be added and il look into adding it soonish.

**Comment by Sylvansnake** [comment]
In the newest version, the Scathe combo isn't working. I tick the Fire 1/3 switch and the Scathe combo opens with Fire 1 and not Fire 3. Unticking the Fire 1/3 switch makes Fire 4 the combo opener. The Fire 1/3 switch correctly changes the base Fire 1 to Fire 3, just not in the Scathe all-in-one combo. Also, the Scathe combo isn't properly switching to the ice phase when mp is depleted. I have to manually cast an ice spell to start the ice phase.

**Comment by Nik-Potokar** [comment]
If you want mostly auto enable everything but if you only tick stance changer + it's subcombos and not aspect feature you will have to swap stance manually since that's how it was intended for you to have control over the stances.

**Comment by Sylvansnake** [comment]
I mostly ticked everything except the conflicting features and it's not doing what it should be doing for me. Not exactly sure what the issue is. I've been using your combo tool for several other jobs and it works well. Just blm seems to get stuck on the all-in-one combo. So for now, I'm just using the Fire 1/3 switcher and Blizzard 1/3 switcher on separate buttons, 2 more buttons for Fire II, Blizzard II then also doing Thunder manually. Being able to pop the Fire III procs instantly is probably the most important feature for me, so it's still worth using though. Could be something I'm doing wrong. I'll try some different setting later, see what happens. But thanks for this tool, anyway.

**Comment by Nik-Potokar** [comment]
@Sylvansnake Mind adding me on discord (Aki#9251) so that I can take a deeper look on what the issue could be.

Because I've tested it and it still does work as intended.

Since for singe target:

Scathe changes based on your stance:

(Means you manually cast 1st fire3) If in fire it will change to fire4 until you are 6sec or below on gauge elemental timer where then it will change to fire1 to refresh the elemental timer duration and go back to fire4 > into despar when below 2k mana> (if aspect feature is not turned on) you will have to manually do blizzard 3 to get into ice stance > scathe changes to blizzard 4 >  (if aspect feature is not turned on) then you have to manually cast fire 3 and then it repeats.

But if aspect feature is on once you cast your 1st fire/ice spell it should automatically swap without needing for any manual adjustments.

And I've tested AoE as well at both lower levers as higher 

Everything is on flare(which should change to blizzard 2/ high blizzard depending on your level) and it should just rotate like this:

Blizzard>freeze>dot>fire2/HF>less than 7k mana> flare until out of mana>blizzard>repeat

That is the expected behavior.
