### ISSUE TITLE
[MNK] Request: Dragonkick/Bootshine

### ISSUE THREAD

**Issue by frukbachers** [Nik-Potokar/XIVSlothCombo#259]
Maybe just a minor thing, but:

outside of a fight (and maybe on lower levels without access to form shift) the Monk Bootshine feature will stay on dragonkick even when you don't have a form.

So maybe changing it so that bootshine is bootshine either when no form is up OR when a form and leaden fist are up would be beneficial.

Unsure if I explained it sufficiently, so if there's questions, please let me know.

**Comment by augporto** [comment]
> So maybe changing it so that bootshine is bootshine either when no form is up OR when a form and leaden fist are up would be beneficial.

When you don't have leaden , dragon kick is always a higher potency than bootshine, so making it change to bootshine without the leaden fist buff  or leaden fist without opo-opo or FF , is a dps loss.

DK is 320p and BS is 210p without leaden. 

What makes BS outdps DK is the fact that it gets a guaranteed crit when in opo-opo, because with only leaden the BS potency only raises to 310.
