### ISSUE TITLE
[WHM] Thin Air + Alt Raise Issue

### ISSUE THREAD

**Issue by Critiko** [Nik-Potokar/XIVSlothCombo#287]
Thin Air Raise Feature with WHM Raise Feature alternative does not work as intended. Thin air does not pop up immediately meaning you will most of the time use raise without Thin Air.

It works fine on the non-alternative version.

**Comment by NikkoToska** [comment]
I noticed this as well.  I would also like to suggest a change; when thin air has a charge and you are not under the effect of thin air, it should replace raise.  So [Raise] is replaced by [Swiftcast] then [Thin Air].  If [Swiftcast] is on cooldown, then [Thin Air] shows. If [Thin Air] has no charges or you have the buff, [Raise] shows.

This is different than how it is now because if [Swiftcast] is on cooldown, [Raise] shows and you have to activate [Thin Air] manually on a different button.
