### ISSUE TITLE
[NIN] Sugestion for "Simple Mudras" and a few Bugs

### ISSUE THREAD

**Issue by Megasder** [Nik-Potokar/XIVSlothCombo#309]
Im leveling ninja to 90 and decided to try the ninja options in the plugin, everything seems fine (except the option 123 Dream to Assassinate, since we dont have assassinate ready anymore and option 127 Kassatsu Chi/Jin that breaks Chi and dont let you use it unless you have Chi stacks and the option 129 Aeolian to Ninjutsu Feature that it seems to do nothing)

The thing with simple mudras is that its a mess because you change to single target to AOE in the same button, yes at the end you will learn the combos, but I think it can be improved.

**This is how Simple Mudra Work Now:**
_Ten - Fuma Shurirken - Hyoton - Doton
Chi - Fuma Shurirken - Katon - Suiton
Jin - Fuma Shuriken - Raiton - Huton_

I want to make some changes:

**Before level 45 (that you unlock Jin)**

_Ten - Fuma Shuriken - Raiton
Chi - Fuma Shuriken - Katon_

So before level 45 Ten is your single target mudra and Chi is your AOE mudra.
(Maybe make that at level below 45 Jin becomes Chi so its easier for the muscle memory because after level 45 Jin becomes the AOE)

**Now after level 45**
_Ten - Fuma Shuriken - Raiton - Suiton
Chi - Fuma Shuriken - Hyoton - Huton
Jin - Fuma Shuriken - Katon - Doton_

So after level 45 Ten is still your single target mudra. but Chi is your miscenally mudra (Hyoton slow and Huton buffs) and Jin is your aoe mudra (thats why I said before to change Jin to Chi below 45)

I wanted to make Chi still the AOE mudra, but the mudra combination made it impossible to do (since if you start with Chi you cant end with doton)

Now lets see the other skills that use mudras:

**Kassatsu - You only want to use that skill with the 2 higher damage ninjutsu**

**Kassatsu (Before level 76) you higher ninjutsu are Raiton and Katon so**
_Ten - Fuma Shuriken - Raiton - Raiton (So you use always Raiton)
Chi - Fuma Shurirken - Katon - Katon (So you always use Katon)
Jin - Whatever_

**Kassatsu (After level 76) now your higher ninjutsu are Hyoton and Katon (because of the Enhanced Kassatsu Trait) so**
_Ten - Fuma Shuriken - Hyuton (Hyosho Ranryu)
Chi - Fuma Shuriken - Katon (Goka Mekkyaku)
Jin - Whatever_

**Ten Chi Jin - Even if there are lots of combination we want principally 2, the single target and the aoe**

_Ten (single) - Fuma Shuriken - Raiton - Suiton (like the option 126 Ten Chi Jin Feature)
Chi - Fuma Shuriken - Katon - Doton_

I'm not a Ninja main so I dont know if Ten Chi Jin is useful for other things.

Well these are my sugestion, if they can be done good, if not well at least I tried to write them :)

**Comment by k-kz** [comment]
I don't have NIN levelled and have never played it  - is the `Dream to Assassinate` feature defunct now, then?

Unfortunately most of what you've written is completely over my head right now but the thorough write-up is really appreciated and I'm sure one of the contributors can do something with it!

When I do eventually level NIN, I'll be able to look at things you've brought up from the "levelling" perspective too, though :]
Also feel free to make a PR yourself if you're up for it!

**Comment by augporto** [comment]
Heya @Megasder , I was the one that wrote the Simple Mudra feature :) .

Although at the time it was only meant as a general helper rather than a specialized feature, I see what you are talking about and I agree that it can be improved like you said, and taking a mudra and making it the main ST and AOE ones is a nice idea too.

I will look up what I do about it on the lower levels since I`m done with the changes I wanted to make for MCH, but I cant guarantee it to be ready this weak, because I'll have a busy week T.T and my NIN is only lv 72 atm :( , I need to lv it too xD.

About the Ten Chi Ji skill , if I'm not mistaken the simple mudra feature do not interact with it, since the changes to the mudra buttons are all on the Ten Chi Ji skill itself , I think , I maybe be wrong though.

@k-kz yes I think the `Dream to Assassinate` is defunct now, because `Assassinate ready` doesn't exist anymore and `Assassinate` itself gets upgraded to `Dream within a Dream` later.

**Comment by Taurenkey** [comment]
Dream is just an upgraded version of Assassinate now as opposed to 2 seperate buttons. It's upgraded at 56 with a trait and there's no need to proc it anymore.

As to the combos, it's something I tackled myself. I'm not a contributer but I _have_ been making my own adjustments to the plugin where I see fit, for personal use of course. I ended up baking the mudras into a combo path instead of using simple mudras (I'm taking the plugin name _very_ literally) so that way I could take into account things like Trick Attack cooldown and adjusting Kassatsu when it gets the jutsu upgrades at 76.

Code below is for single target jutsus. I haven't bothered putting in a path for Huton since at 60 onwards there's an ability that grants it and before that the simple mudras feature already defaults the Jin path to it.

```
if (IsEnabled(CustomComboPreset.NinAeolianMudras))
                {
                    if ((!GetCooldown(NIN.TrickAttack).IsCooldown || GetCooldown(NIN.TrickAttack).CooldownRemaining <= 3) && level >= 45)
                    {
                        if (HasEffect(NIN.Buffs.Suiton))
                        {
                            return NIN.TrickAttack;
                        }
                        if (!HasEffect(NIN.Buffs.Mudra) && GetCooldown(NIN.Chi).RemainingCharges > 0)
                            return OriginalHook(NIN.Chi);

                        if (level >= NIN.Levels.Ten && OriginalHook(NIN.Ninjutsu) == NIN.FumaShuriken)
                        {
                            return OriginalHook(NIN.TenCombo);
                        }

                        if (level >= NIN.Levels.Jin && (OriginalHook(NIN.Ninjutsu) is NIN.Katon or NIN.GokaMekkyaku))
                        {
                            return OriginalHook(NIN.JinCombo);
                        }

                        if (OriginalHook(NIN.Ninjutsu) is NIN.Suiton)
                        {
                            return OriginalHook(NIN.Ninjutsu);
                        }
                    }

                    if (!GetCooldown(NIN.Kassatsu).IsCooldown && !HasEffect(NIN.Buffs.Mudra) && level >= 50)
                    {
                        return NIN.Kassatsu;
                    }
                    
                    if (level >= 76)
                    {
                        if (!HasEffect(NIN.Buffs.Kassatsu))
                        {
                            if (OriginalHook(NIN.Ninjutsu) == NIN.Raiton) return OriginalHook(NIN.Ninjutsu);
                            if (OriginalHook(NIN.Ninjutsu) == NIN.FumaShuriken) return OriginalHook(NIN.ChiCombo);
                            if (HasEffect(NIN.Buffs.Kassatsu)) return NIN.JinCombo;
                            if (GetCooldown(NIN.Jin).RemainingCharges > 0) return NIN.Jin;
                        }
                        else
                        {
                            if (OriginalHook(NIN.Ninjutsu) is NIN.HyoshoRanryu or NIN.Raiton) return OriginalHook(NIN.Ninjutsu);
                            if (OriginalHook(NIN.Ninjutsu) == NIN.FumaShuriken) return OriginalHook(NIN.JinCombo);
                            return OriginalHook(NIN.Ten);
                        }
                    }
                    else
                    {
                        if (OriginalHook(NIN.Ninjutsu) == NIN.Raiton) return OriginalHook(NIN.Ninjutsu);
                        if (OriginalHook(NIN.Ninjutsu) == NIN.FumaShuriken)
                        {
                            if (level < NIN.Levels.Chi)
                                return OriginalHook(NIN.Ninjutsu);

                            return OriginalHook(NIN.ChiCombo);
                        }
                        if (HasEffect(NIN.Buffs.Kassatsu)) return NIN.JinCombo;
                        if (GetCooldown(NIN.Jin).RemainingCharges > 0) return NIN.Jin;
                    }


                }
```

I made the mudra feature a child to the pre-existing NinjaAeolianEdgeCombo feature, so it can be turned off and on as seen fit.

**Comment by augporto** [comment]
@Taurenkey I see , that is like the Simple features of the physical ranged classes.

Dunno if we keep it separated of the main combo or add it in like you did, or both, since I like the one button approach too myself, but maybe there are people that like it separated as it is now.

@k-kz what do you think?

**Comment by Taurenkey** [comment]
@augporto That's been my main goal with my own tweaks, to try and make as many jobs as "Simple" as possible. I try and boil them down to 2 buttons. A single target and an aoe target button. If we like this implimentation, I also done a "Simple AoE" for NIN which was more of a pain given the delay Doton buff has after being cast.

**Comment by k-kz** [comment]
@augporto Can't speak for the code as I don't know the combo chains and can't even tell the names apart haha, but I personally am on the side of putting "true one-button functionality" as a separate, standalone feature.

For example, I've put a bunch of improvements onto the Simple DNC features, but I don't use it myself as a DNC main, and like to be able to use the original, separate features.
One button modes are great for when you're preoccupied or feeling lazy, but they also take away a lot of gratification of playing the jobs, so I've pushed towards just saturating the available options and feature combinations.

**Comment by augporto** [comment]
> @augporto That's been my main goal with my own tweaks, to try and make as many jobs as "Simple" as possible. I try and boil them down to 2 buttons. A single target and an aoe target button. If we like this implimentation, I also done a "Simple AoE" for NIN which was more of a pain given the delay Doton buff has after being cast.

@Taurenkey could link the snippet of the simple aoe too? And would you mind if I use them to cook something ?

> @augporto Can't speak for the code as I don't know the combo chains and can't even tell the names apart haha, but I personally am on the side of putting "true one-button functionality" as a separate, standalone feature.
> 
> For example, I've put a bunch of improvements onto the Simple DNC features, but I don't use it myself as a DNC main, and like to be able to use the original, separate features. One button modes are great for when you're preoccupied or feeling lazy, but they also take away a lot of gratification of playing the jobs, so I've pushed towards just saturating the available options and feature combinations.

The code seems ok , yea I think the same way on the "true one button", I think having both options is the best course of action.

**Comment by Taurenkey** [comment]
@augporto I'm slowly learning how to use Github, so bear with me :)

I have other changes stashed away for other jobs but I'm gonna test the waters a bit with what people might want. I've really enjoyed making my own features, but I will say I made enemies with Doton because the buff doesn't apply instantly. I had to take some creative liberties by adding in a freaking last used jutsu tracker. I rabbited way too many times getting it to work.

**Comment by augporto** [comment]
> @augporto I'm slowly learning how to use Github, so bear with me :)
> 
> I have other changes stashed away for other jobs but I'm gonna test the waters a bit with what people might want. I've really enjoyed making my own features, but I will say I made enemies with Doton because the buff doesn't apply instantly. I had to take some creative liberties by adding in a freaking last used jutsu tracker. I rabbited way too many times getting it to work.

Hah I know the feeling , I had problems tracking other things in other jobs too.

**Comment by Megasder** [comment]
Hi, thank you all for all your comments, I put the comment before leaving and now it has this many comments XD
I dont really know anything about code, that is why it was okay with me if you ignored my suggestions, seeing that you guys take this seriusly makes me happy, even if you say you are not going to start this week its ok for me.
im sorry I cant help with the code... but if I see other problems or have more suggestions I will put them on the main page :D

**Comment by Taurenkey** [comment]
> that is why it was okay with me if you ignored my suggestions

It's less that I ignored it and more that mudras are already a pain in the backside. The ethos behind this plugin is to make things simpler and leaning on the lazier side, mudras automatically disagree with that. Without creating a whole bunch of alternative `Simple Mudra` features for each combo path (each jutsu already has at least 2 different paths as is) it's ultimately going to be easier just to bake them into other features. I don't know if @augporto made the feature based off how they do mudras or whatever but it's ultimately a subjective how each person chains their mudras.

From a coding point of view though, it _was_ easier to keep all the AoE jutsus on the same chain. You'll notice that the AoE jutsus do share a common starter:

- Jin -> Ten = Katon **and** Goka Mekkyaku
- Jin -> Ten -> Chi = Doton

So while you wanted `Chi` to be your "AoE mudra", that doesn't lead into Doton at all. Reason it was better to do it this way was in case of overlapping sequences (it happened a lot to me in early testing until I decided to put them all on the same chains) and therefore rabbitting.  However when it comes to the single target paths, they made it awkward on purpose.

- Ten -> Chi or Jin -> Chi = Raiton
- Chi -> Jin or Ten -> Jin = Hyosho Ranryu

None of these share a common path. They start the same but they always diverge after the first mudra. Now, from a coding point of view, I've already proven that context sensitivity based off `Kassatsu` buff is possible, so that would make your best single target mudra actually be `Ten` in that case. But now we have to consider `Suiton` for `Trick Attack`

- Ten -> Chi -> Jin or Chi -> Ten -> Jin = Suiton 

The answer should be to continue with `Ten` as the base mudra since it follows the same combo path as Raiton but with `Jin` at the end. Poor `Chi` has become obsolete at this point unless it is to be the `Hyoton` and `Huton` path. That's just my logic to dealing with mudras. I could do an alternate version of `Simple Mudra` feature that follows _this_ logic if @augporto doesn't have any sort of objection (this was his feature originally after all).

**Comment by augporto** [comment]
@Taurenkey no objection at all, like I said earlier the simple mudra was conceived to simplify it to a point of only not getting rabbits, for those that do not use single combo buttons. 

When I did it the 1st time I was looking at a suggestion someone posted and the cheat sheet chart on the balance for the paths, at first it was not meant to be anything anymore than that, and one path only.

I agree with  your analysis and the way you tackle the implementation to "weave" the ninjutsus in the combo chain, to be fair I even prefer it. 😄

**Comment by NikkoToska** [comment]
When I originally suggested the idea, I came up with two alternative patterns.  It seems like the alternate one would line up with single target vs. AoE in rotation.  If you're willing to do the alternate coding changes @Taurenkey, maybe this will help: https://github.com/Nik-Potokar/XIVSlothCombo/issues/266#issue-1140244694

My original intention in suggesting this wasn't for optimal rotations, but just to prevent bunnies and make it simple for casual players.

**Comment by Taurenkey** [comment]
> When I originally suggested the idea, I came up with two alternative patterns. It seems like the alternate one would line up with single target vs. AoE in rotation. If you're willing to do the alternate coding changes @Taurenkey, maybe this will help: [#266 (comment)](https://github.com/Nik-Potokar/XIVSlothCombo/issues/266#issue-1140244694)
> 
> My original intention in suggesting this wasn't for optimal rotations, but just to prevent bunnies and make it simple for casual players.

I've learned quite a lot from doing stuff with this plugin and if there's _**one**_ thing I've learnt it's that nothing is actually impossible as far as combo routes go. I'm pretty much at the point now where if it's possible for an actual player to do manually, I can program it into a feature. So back to mudras, from a casual perspective it's less about preventing rabbits and more user preference. Because of the subjective nature of the topic, I can see myself taking the feature to "the next level" as it were by incorporating user configured values, similar to other jobs. The plugin already offers a myriad of user-selected values through the configuration service so hooking into that to provide users an option for their mudras seem feasible. 

It'd still be a set amount of configurations (I don't think it'd be sane to do all possible combos) but instead of them being completely different features, it'd be built into one and the route is switched based on user preference. 

![image](https://user-images.githubusercontent.com/30053704/160446118-f4b5e157-b7ca-461e-a9e1-89873bb7b78b.png)
 Attached screenshot of idea. I have it at the stage of being able to work, so it's just fleshing it out to be descriptive now.

**Comment by k-kz** [comment]
@augporto @Taurenkey @NikkoToska @Megasder 

Since this discussion has picked up a bit, I've spoken to Aki and set up a Discord server so we can do all this a bit more easily.
Will integrate it with the GitHub soon enough, still setting other stuff up.

https://discord.gg/xT7zyjzjtY

**Comment by k-kz** [comment]
Fixed/enhanced in various updates from @Taurenkey.
