### ISSUE TITLE
[Tanks] Simple Defensive CDs

### ISSUE THREAD

**Issue by Taisaku-101** [Nik-Potokar/XIVSlothCombo#439]
It would be really nice to have all the non invulnerable mitigation CD's on one button. It could start with the biggest % ones and work down.

**Comment by NikkoToska** [comment]
I've been thinking about this and will probably do it as a 'Simple Mitigation' feature.  I would love to hear more feedback from you and other tanks in terms of CD priority for each job.  And I'll probably make an option for things like Sheltron and TBN for specific jobs.  Should they take priority over regular CDs or weaved somewhere in the middle?

**Comment by Sylvansnake** [comment]
I have macros loaded with the mitigation skills for my tank jobs. Paladin is my main tank. As a general rule, I put mitigations with shorter cooldowns in higher priority, saving long cooldowns for last. Since acquiring Holy Sheltron, I rarely use my other cooldowns because it's so good. But I keep them on macro anyway. My mitigation order is: Sheltron, Rampart, Reprisal, Sentinel.

I'm not sure what the efficiency is of stacking Rampart and Sentinel together, so that's why I put Reprisal between them since it's an enemy debuff. I think adding a panic button feature to tank jobs might be useful. If a tank's HP drops to a very low level, add their invuln cooldown to the main combos. But for normal mitigation skills, I think it would be best to just have a separate button for those, like if Sentinel is on cooldown it changes to Rampart or Reprisal. The tank would probably prefer to have more control over when to use them.

**Comment by NikkoToska** [comment]
I'm making it customizable.  Starting with WAR as a proof of concept, and I'll probably wait until after the update to do the rest in case of changes.

**Comment by Taisaku-101** [comment]
These are great ideas. I would love to try out the WAR one. Personally I use greatest reduction to least reduction. Maybe it could have a standard of CD timer with sub options for priority, something like the fan dance system for dancer. Also having the ability to not have a CD in the rotation would be great. Personally as a DRK I would like reprisal, TBN, and Dark Missionary to not be on the one-button but everything else to be in order of mitigation %.

**Comment by NikkoToska** [comment]
How I have it working now in testing is that you can set the priority to 0 and it will skip that ability.  Everything else you can assign a priority to and it will appear in that order.  This means that I can add all the possible mitigations and if you don't want to include it, it starts off by default.  When all CDs are used, the next to come off cooldown will appear so you know what ability can be used next.

**Comment by Taisaku-101** [comment]
Oh yeah, that sounds great!

**Comment by Sylvansnake** [comment]
Nice concept Nikko. I like the idea, so when might we get to try it in the live release?

**Comment by Taisaku-101** [comment]
Curious to see if this was still on the back burner because it needs more consideration or just low priority? Just wondering, not trying to rush at all.

**Comment by NikkoXIV** [comment]
We were holding off on it for the moment, but we're almost back to the place where we can consider it.  The biggest challenge is how to implement it in a way which prevents abuse.  And by abuse I mean someone carelessly using it to blow all their cooldowns and ruin a pull.  While at the same time we also don't want to prevent someone from using a cooldown when it's necessary, so there has to be some additional considerations there.  Prevent spam while not restricting valid use.

**Comment by Rabalaba** [comment]
make a function for incoming damage taken per second, set a threshold for say 10 percent of hp over 5 seconds, if not healed set bool to true, if you were healed bool set false.  Set double equal to current damage reduction, if less than wanted amount cycle through available cooldowns, each cooldown used will increase the current damage reduction and set the damage reduction bool to false preventing the next defensive from being used.  I have example code if needed.

**Comment by k-kz** [comment]
Closing this for now as it's unlikely to be added any time soon, if at all.
Also want to note that we aren't interested in incorporating incoming DPS tracking into the plugin as a means of handling this.
