### ISSUE TITLE
[SGE] Diagnosis/Prognosis - Always Eukrasian Option

### ISSUE THREAD

**Issue by thoccavelli** [Nik-Potokar/XIVSlothCombo#445]
Love your addon fork!  For Sage, could you please add option to ALWAYS make diagnosis & prognosis as eukrasian versions, no matter what the friendly target HP is?  

1. diagnosis button _always_ casts eukrasia  -> eukrasian diagnosis
2. prognosis button _always_ casts eukrasia -> eukrasian prognosis

Sage tactics often involve proactively turning on eukrasia during downtime between pulls (when HP is 100%), then casting eukrasia diagnosis/prognosis as soon as pull starts.  There are times during boss fights (like incoming raidwide damage) when you want to proactively refresh eukrasian diagnosis/prognosis even if everyone's health is 100%.

At high levels, Sage essentially never uses the regular diagnosis & prognosis spells since they are a DPS loss, inefficient use of OCG, and readily surpassed by Sage's oGCD healing abilities such as the -chole abilties.  

Thank you!

**Comment by Sylvansnake** [comment]
I don't think it would be good to always use Eukrasia for every heal. For one thing the healing component for the Eukrasian version is weaker. There might be a time when you want to have a stronger heal with no shield. Perhaps an option to check for the existence of a shield on the target could be done. If the target has no shield, it would cast Eukrasia. If a shield is already on the target, then just a normal heal. But I'm not sure it would work with mouseover healing.

**Comment by Tsusai** [comment]
Here's my two cents.
Prior to Endwalker, AST had an instant cast shield, with it's potencies different than SCH due to it being instant cast (also no crit layer).  In Endwalker, Sage's Barrier values are the same as Scholar, and even do the crit layer.

Having played both Sage and Scholar, I feel the overall cast times are near identical (Eukrasia + Diagnosis vs Aldo).

I consider this request to be very exploitive of game mechanics. If it worked, it would break the balance between the two classes by giving Sage pure, unfettered instant barriers, by bypassing the core concept of the class.  It would become a true instant cast barrier with possible crits and a super fast recast (I believe the recast is halved between Eukrasia buff and it's combo actions).  If Scholar wasn't killed off by Sage as it is, it would be 6 ft under after this.

Side note: Even the Sage DPS feature calls Eukrasia, not Eukrasia Dosis.

**Comment by Dedoooo** [comment]
>  If the target has no shield, it would cast Eukrasia. If a shield is already on the target, then just a normal heal. But I'm not sure it would work with mouseover healing.

it does not work with mouse over. i believe it should work similar to medica ii, aspected helios by first detecting if it has the status THEN changing it to regular spell.

you don't diagnosis as much as you eukrasian diagnosis and i personally would like that as an option too.

**Comment by Tsusai** [comment]
#891 Should be a decent in the middle solution. Eukrasia will combo itself to whatever of the 3 Eukrasians you would like. Also you can use just the shielding feature of Single Target and AoE Heals, set to 100% to force shields at all times.
