### ISSUE TITLE
[WAR]Storm's Path has not changed to Fell Cleave

### ISSUE THREAD

**Issue by Rigaln** [Nik-Potokar/XIVSlothCombo#486]
Even though the gauge is over 50.
Storm's Path has not changed to Fell Cleave

AOE's are changing properly.

![image](https://user-images.githubusercontent.com/97243504/163655211-aafd0f79-1f31-4ade-b436-f9cea7ec9755.png)
![image](https://user-images.githubusercontent.com/97243504/163656324-a081251d-091f-451a-a021-580061ea8c13.png)
![image](https://user-images.githubusercontent.com/97243504/163655361-b4bf81c6-1073-4168-b0bd-2470e2217d11.png)

**Comment by damolitionn** [comment]
Do you remember what the cooldown for Inner Release was at that point?

**Comment by Rigaln** [comment]
I'm reading it in Japanese with machine translation.
I didn't understand much.
So that's what you meant by pool.
Thank you.

But there are times when the gauge reaches 100.
I'm curious about that too.

**Comment by damolitionn** [comment]
It'll stay at 100 until the next skill you have has a chance to cap it then it'll spend it before your gauge overcaps. This way you can delay Fell Cleave by at least 1 GCD and hopefully push it closer to raid buffs. This happens when say once you finish your combo you're at 100, it won't automatically fell cleave when it's time to heavy swing as heavy swing doesn't increase beast gauge. It will though before Maim as Maim will overcap it.

**Comment by k-kz** [comment]
See comment chain
