### ISSUE TITLE
[DNC] Simple Dancer Panic Heal options

### ISSUE THREAD

**Issue by dawn-star** [Nik-Potokar/XIVSlothCombo#551]
Hi,

DNC currently has a feature for weaving heal abilities under certain thresholds:

                    // Simple ST Panic Heals
                    if (IsEnabled(CustomComboPreset.DancerSimplePanicHealsFeature))
                    {
                        if (PlayerHealthPercentageHp() < 30 && curingWaltzReady)
                            return DNC.CuringWaltz;

                        if (PlayerHealthPercentageHp() < 50 && secondWindReady)
                            return DNC.SecondWind;
                    }`

Could we have these as separate suboptions?

The relatively short CD of Curing Waltz allows for pretty liberal use, and I enjoy having this feature weaved by the plugin, but there are certain scenarios where I would prefer to hold Second Wind for specific mechanics or emergencies.

In particular Life’s Agonies in P3S without AST cheese, Second Wind can be the difference between life and death if it would take you from 99% to 100% HP

**Comment by dawn-star** [comment]
Additionally, having sliders to adjust the threshold would be nice.

**Comment by k-kz** [comment]
> Could we have these as separate suboptions?

The feature is unlikely to be split due to its intended use and Simple DNC already being bloated with sub-options.

> In particular Life’s Agonies in P3S without AST cheese, Second Wind can be the difference between life and death if it would take you from 99% to 100% HP

For edge-case scenarios as you described above, you would be expected to manually use an action when it's that far outside of the intended use-case (e.g. Second Wind at 99%HP). It is called "Panic Heals", remember!
Curing Waltz is at 30% currently because it's expected for you to find a good manual use where the party is standing together before the feature would use it.

> Additionally, having sliders to adjust the threshold would be nice.

I have thought about adding sliders to them, but *to an extent* this also sort of goes outside the intended use of the feature.
For application of this in Savage and Ultimate, you are expected to use these heals manually before thresholds are reached, usually - the feature is supposed to back you up while you're in a burst phase and not paying enough attention to them, for example.

All this being said - I will chat to some of the other DNC players who test the plugin for us and get their thoughts on changing the priority order/thresholds of the heals.
