### ISSUE TITLE
[NIN] Mug, Bunshin, Trick Windows and Ninki Pooling

### ISSUE THREAD

**Issue by Yaboije** [Nik-Potokar/XIVSlothCombo#589]
[Out of Combat] Huton 11s -> Hide -> Opener ->
[Pre-Trick Setup] Suiton (kassatsu) -> Spinning Edge (oGCD) -> Gust Slash (mug+bunshin) -> Aeolian Edge (trick) -> 
[Trick Window] Kama (dream) -> Hyosho -> Raiton (TCJ+FS,RT,ST,MS) -> Raiju (bhava) x2 -> Raiton -> Raiju

The current priority accomplishes most of this except the pre trick window setup any chance it can be toggled or would it conflict too much within the single target rotation that currently exists?

Can we also have a ninki pooling option similar to the kenki pooling in the SAM options? (Use Bhava at 85 ninki or higher)
Having ninki be dumped at 50 by default makes it harder to line up bunshin without mug off cd.

Great work so far!

**Comment by Taurenkey** [comment]
Unfortunately due to how complicated NIN is on a fundamental level with various different states (Huton timers, Jutsu charges, casting mudras etc.) combined with failure states (Rabbiting your jutsus) it's going to take some time before we can get a properly functioning NIN opener.

Good news is though it's in the works and it _does_ work good in simple situations such as raid bosses where you'll have all your CDs up and you can do a pre-pull, but it's currently a shambles in other aspects of PVE like 4-man dungeon trash or between pulls. Because the NIN opener relies heavily on having jutsu charges and Kassatsu, having them out of alignment causes a scuffed opener. 

I can look at addressing Ninki pooling and apply that to the `Simple Single Target` feature as an option.

**Comment by k-kz** [comment]
Addressed in #594
