### ISSUE TITLE
[GNB] Sonic break suggestion

### ISSUE THREAD

**Issue by opengrip** [Nik-Potokar/XIVSlothCombo#59]
Can we get sonic break on the main combo within no mercy instead of tied to the no mercy button. It doesn't make much sense the way it is currently since Sonic Break is a weaponskill and requires a GCD. Changing Sonic break to behave like double down would be much better. This would also clean it up more when doing dungeons and trash pulls... i wanna no mercy and AOE spam... but I keep seeing sonic break on my no mercy button which I would never use in this situation. I know I could turn it off but I do like having bow shock linked to no mercy.

**Comment by nativepapaya** [comment]
Well, the main reason it was setup this way is because they both have a 60 second CD and you never want to use sonic break outside of no mercy as it would be a big dps loss.

As far as trash pull though, i don't see the issue? You can no mercy and sonic break just fine before spamming AoE, which again you want to do under no mercy anyways.

I think it is great the way it currently works.

**Comment by opengrip** [comment]
I understand the logic of having it only in no mercy but the fact that its a GCD tied together on the same button makes it super clunky for me. Its the exact same thing as double down which you also wouldn't want to use outside of no mercy. And honestly if you can just add sonic break to the double down feature it would be way better. I keep all my GCD sperate from my oGCDs so that when playing it makes more sense to keep track of the flow. For example no modifier for a GCD.... then I shift key for an oGCD or 2. Back and forth... Having sonic break be a GCD under a oGCD icon really messes with that when it should be used in your main combo button since that consists of all GCD's. I hope that makes sense.

**Comment by opengrip** [comment]
Another way to look at it... is most players spam follow up GCD button... in most cases that will be the main combo or the AOE combo... They don't spam oGCD longer then the GCD runs... Since they don't want to clip there next GCD... so having a GCD on a button that is used mainly for oGCD goes against that muscle memory.

**Comment by opengrip** [comment]
Any word on this suggestion?

**Comment by Nik-Potokar** [comment]
Il do some testing! Could add it as separate option and then everyone can decide which version of the option they wanna use

**Comment by opengrip** [comment]
That would be amazing thank you!

**Comment by Nik-Potokar** [comment]
So ive added bowshock after sonic break and it does feel better! 

Could you give me some more detail how you want it to be on the double down feature (since my GNB isn't 90 i can't test that)
You want it before Double down or after?

Also if you want you can add me on Discord (Aki#9251) since i would love to have an GNB player to test stuff/get suggestions from
