### ISSUE TITLE
[SMN] Simple Summoner Feature

### ISSUE THREAD

**Issue by Nik-Potokar** [Nik-Potokar/XIVSlothCombo#60]
Anyone that can help test this in-game and report back here or directly to me on discord (Aki#9251)
it would be greatly appreciated.

Added a simple summoner combo similar to Samurai one but way more condensed.

Features 
Everything is on one button (Currently only for Single Target).
Fester, ED, Deathflare, Enkindles, EGI Skills, Buff...

## What i want to improve (Need Help):
* Smoother oGCD Weaving solution
* Bug Reports

## What is coming:
* AoE Version
* Multiple EGI Summoning combinations (Order)
* Low Level Checks 

https://github.com/Nik-Potokar/XIVSlothCombo/blob/0d8b9a5f2b75e9e9a7c01e2f56567f7d6952ad8c/XIVComboExpanded/Combos/SMN.cs#L189

Any feedback is greatly appreciated!!! <3

**Comment by rushtothesun** [comment]
The only glaring thing I saw is that SimpleSummoner Option 1 needs to be changed. Spell Speed reduces Summon Bahamut's CD and with the current logic Searing Light will only be used when Bahamut is ready to be casted. With my current gear this means that when the 2nd Searing Light is coming up: Bahamut will be off CD while Searing is still on CD -> Bahamut will be used and Searing Light won't be used until the next Bahamut. I can imagine fights with deadtime will also be an issue. Such as having Phoenix ready and Searing Light up because of a transition. You'd lose an entire use of the buff there as well.

For Enkindle/Deathflare/Fester I'd say try to make it go off as close to the end of the gauge as you can to make sure all of that is being used while raid buffs are up. This might be tricky to do though because of Spell Speed again.

It's not easy to do an everything combo for Summoner because there's a bit of decision making on when to use the abilities which is also why a lot of the current combos for Summoner can be DPS losses depending on the circumstance.

**Comment by dnorthrupva** [comment]
I'll start going over it but one thing I noticed:

At a quick glance, I am fairly confident the Carbuncle Summon Feature will never be triggered as part of this.

If Buff -> Searing Light, only trumped if Bahamut is down.

Additionally, the Egi logic needs some work. Each succession tries to summon Rank 1 of the appropriate Egi. If you're spamming the button, this is actually fine (I still haven't figured out WHY that works).

To replicate, summon Bahamut and let it time out. You'll go to Summon Titan - But it'll be Rank 1. Don't hit anything for a second, and then when you go to hit it, it'll just be ignored as it isn't a valid key for you anymore. I think it'll need a daisy chain of if, or a function to respond which to summon based on level.

**Comment by thisnameistoolo** [comment]
You mentioned sending you a message on discord, but I don't see any links to a discord channel or your private discord anywhere on this repository. I know this isn't the best place to write this message but I literally can't find your discord contact info anywhere.

**Comment by Nik-Potokar** [comment]
Thanks for all the feedback so far

@rushtothesun 
About the spell speed issue i think id have to see the high sps rotation and go from there maybe add another option if you are a sps summoner so you can just toggle.

> At a quick glance, I am fairly confident the Carbuncle Summon Feature will never be triggered as part of this.
> 
Right it will only break if you die but will add a fix for this 

> Additionally, the Egi logic needs some work. Each succession tries to summon Rank 1 of the appropriate Egi. If you're spamming the button, this is actually fine (I still haven't figured out WHY that works).
> 
Il be adding level checks/originalhook to solve the rank1 summon issues (Since i been testing on non 90 SMN)

@thisnameistoolo 
Oh and i've added my discord above i guess i forgot to type it lol

**Comment by SkyAurora** [comment]
Regarding the searing light with bahamut timing issue, maybe add another Ruin III in the opener after searing light. The opener on The Balance Discord actually has it like that. Ruin III > Searing > Ruin III > Bahamut

**Comment by rushtothesun** [comment]
> Regarding the searing light with bahamut timing issue, maybe add another Ruin III in the opener after searing light. The opener on The Balance Discord actually has it like that. Ruin III > Searing > Ruin III > Bahamut

The opener isn't this issue.

**Comment by armourine** [comment]
Is it possible to change an unslotted skill to Ruin III so that I can manually delay bahamut by 1 cast to have alignment with searing light?

**Comment by Iaotle** [comment]
@armourine that's what the Ruin III mobility option does though I have no idea if it works for your use case.

**Comment by armourine** [comment]
i tried that option but i couldnt get a cast off, do you know what combinations of options it works with?

**Comment by Iaotle** [comment]
Like it says on the option it will probably break most options with R4. I only have Egi Attacks/Mountain Buster/Fester/Painflare/Reminder features enabled and it works perfectly.

**Comment by armourine** [comment]
I see that is unfortunate. Is it possible to replace Sleep with Ruin III instead?

**Comment by DurzoThorn** [comment]
> I see that is unfortunate. Is it possible to replace Sleep with Ruin III instead?

Can agree this would be an awesome addition as for some fights I need to delay bahamut by two or three gcds so searing lines up with mechanics for group damage to beat enrage check p4s part 2 for example. Only option for me currently is to disable some features or try to rely on ruin 3 mobility feature but it seemed to only work for 1 cast sometimes not sure if it is registering on a 1 charge type system since it's replacing ruin 4.

**Comment by Nik-Potokar** [comment]
So what I can do is move everything off ruin3 to one of the gemshine skills and that would free up ruin. il test it out tonight

**Comment by Iaotle** [comment]
@armourine @DurzoThorn the issue is that if you have R3 combos they will replace Ruin III. So if you replace Sleep with R3, you're going to replace R3 with your egi skills etc.

**Comment by Nik-Potokar** [comment]
Added same option but now on ruin1 so it completely frees up ruin3 so far everything still functions like before

**Comment by DurzoThorn** [comment]
You rock I will check it out tomorrow after patch reset!

**Comment by klevox** [comment]
I need help Nothing I click for SMN works. Other jobs work fine is there a guide to setting up SMN? One button would be nice.

**Comment by Nik-Potokar** [comment]
> I need help Nothing I click for SMN works. Other jobs work fine is there a guide to setting up SMN? One button would be nice.

@klevox  As in you cant enable the features ? or when you enable the actual skills wont change?

**Comment by Iaotle** [comment]
@klevox don't worry everything works.

See how that isn't helpful? Provide us with a list of features you have enabled.

**Comment by klevox** [comment]
> @klevox don't worry everything works.
> 
> See how that isn't helpful? Provide us with a list of features you have enabled.

Sorry that was a wrong post. It was about the dalamud not working. On patch day it worked after the update.

**Comment by klevox** [comment]
> > I need help Nothing I click for SMN works. Other jobs work fine is there a guide to setting up SMN? One button would be nice.
> 
> @klevox As in you cant enable the features ? or when you enable the actual skills wont change?

When I try to enable just one feature for testing. Skills do not change, like Carbuncle reminder (enabled) nothing happens. The one button feature enabled nothing else. There is no change to the skill. I have tried every combination of features no skill change at all.

**Comment by Nik-Potokar** [comment]
@klevox Make sure you have Single Target Feature enabled ether Ruin1/Ruin3 and then you need to have a correct skill on your hotbar ruin1/ruin3 (Note: Upgraded skill wont work it has to be directly from your skill page so i recommend just dragging the corresponding skill on hotbar)

If you still cant get it to work you can add me on discord "Aki#9251" so i can help you directly

**Comment by klevox** [comment]
> @klevox Make sure you have Single Target Feature enabled ether Ruin1/Ruin3 and then you need to have a correct skill on your hotbar ruin1/ruin3 (Note: Upgraded skill wont work it has to be directly from your skill page so i recommend just dragging the corresponding skill on hotbar)
> 
> If you still cant get it to work you can add me on discord "Aki#9251" so i can help you directly

Thank you I will try that now. :)

**Comment by Nik-Potokar** [comment]
@klevox Let me know if that fixed it. If not im available to help on discord

**Comment by DurzoThorn** [comment]
Alright so next big feature request that I think should be possible. Can we add energy drain and fester to the main combo and structure it so energy drain is used off cool down as long as no fester stacks remain and fester only shows while buffed by searing light? This should give us the maximum potency out of our ogcds without any real brain power. Only times this wouldn't be ideal is if we are holding searing for a delayed buff window but should just be able to use fester like normal off the main combo button in those situations.

**Comment by Nik-Potokar** [comment]
@DurzoThorn Thats what "Lazy Fester Feature" already kinda does it uses ED/fester during bahamut phase and only uses ED and then saves festers for bahamut phase again.

**Comment by DurzoThorn** [comment]
> @DurzoThorn Thats what "Lazy Fester Feature" already kinda does. It uses ED/fester during bahamut phase and only uses ED and then saves festers for bahamut phase again.

Gotcha the way I read that was it would use festers between gcds in a non optimal method I will toggle it on and let you know how it feels, thanks for the reply.

**Comment by DurzoThorn** [comment]
@Nik-Potokar So I have been playing with the Lazy Fester Feature and my only real issue is that depending on when Energy drain comes off cooldown there can be an occurrence of clipping astral impulse. This is due to the Energy drain coming up in the second half of the weave window and then transitioning to Fester for a double weave that is not actually able to fit thus clipping the next GCD Astral. It might be specific to me since I use XiV Alexander and a turbo mouse button to spam the key every .1 seconds but I was curious if Astral Impulse could lock in as the priority icon 500ms ish before the gcd rolls again to avoid clipping. I would be happy to demonstrate the issue if it isnt clear from the text. Thanks!

**Comment by Iaotle** [comment]
@DurzoThorn if you want to avoid clipping issues entirely you shouldn't use weave combos and should just weave manually.

**Comment by Sylvansnake** [comment]
> So what I can do is move everything off ruin3 to one of the gemshine skills and that would free up ruin. il test it out tonight

This is probably the best solution. Just add both combo chains to Gemshine and Precious Brilliance for simplicity. Then people can still use standalone Ruin/Outburst/Tri-disaster spells as they see fit.

**Comment by lucktacular** [comment]
Hi Aki! I love the plugin. Thanks so much for your work on it :)

I noticed that a recent update has changed the single target rotation to no longer enter the Bahamut phase of the rotation (the AoE one still does). It will just sit there casting Ruin III until I hit the AoE button once to summon Bahamut, then go back to the single target rotation where it goes back to working normally.

Also when it's doing the phoenix portion of the rotation, it will use Energy Drain and generate the aetherflow stacks, but it won't spend them on Fester or Painflare (on the ST and AoE rotations respectively). It spends the aetherflow stacks normally during the Bahamut summon though.

I was wondering if I was doing something wrong, or if any of these changes were deliberate, or if it was simply a bug.

**Comment by Nik-Potokar** [comment]
> Hi Aki! I love the plugin. Thanks so much for your work on it :)
> 
> I noticed that a recent update has changed the single target rotation to no longer enter the Bahamut phase of the rotation (the AoE one still does). It will just sit there casting Ruin III until I hit the AoE button once to summon Bahamut, then go back to the single target rotation where it goes back to working normally.
> 
> Also when it's doing the phoenix portion of the rotation, it will use Energy Drain and generate the aetherflow stacks, but it won't spend them on Fester or Painflare (on the ST and AoE rotations respectively). It spends the aetherflow stacks normally during the Bahamut summon though.
> 
> I was wondering if I was doing something wrong, or if any of these changes were deliberate, or if it was simply a bug.

Make sure you have the correct Option ticked since I've added a choice in between everything on ruin1(this is better for optimization) or ruin3 that you have a correct skill slotted in the hotbar(upgraded skill won't work you have to drag ether ruin1 or ruin3 from skill book onto your hotbar depending on the option you got ticked)

If are still having issue setting it up you can dm me on discord or post a picture of what options you got enabled here and il help you out further.

**Comment by Iaotle** [comment]
Should be working as intended now.

**Comment by MarkusWo** [comment]
> If are still having issue setting it up you can dm me on discord or post a picture of what options you got enabled here and il help you out further.

Unfortunately, I have the same problem as [lucktacular](https://github.com/lucktacular) had.  With my settings, Ruin III just stays Ruin III and never changes to summon Bahamut. I will have to hit the AoE button once to summon Bahamut. Since lucktacular didn't really say how they fixed this I just been looking through all options over and over again to see where there might be a choice. I cannot find the problem, sadly. It doesn't seem to make a difference whether I use "Enable Single Target (Ruin1)" Or RuinIII in the beginning.

I've attached my settings. I have almost everything on since it all seems cool. Thank You if you can look at it.

P.S. lucktacular mentioned discord, do you have your own discord server?

![ffxiv_31032022_004454_159](https://user-images.githubusercontent.com/17179276/160943831-22413f4c-e95a-487a-83e7-704add2322f7.jpg)
![ffxiv_31032022_004500_458](https://user-images.githubusercontent.com/17179276/160943832-d0e5e14a-ae51-4b6e-92a8-8b4fdc47b353.jpg)

**Comment by k-kz** [comment]
@MarkusWo discord server link is on the readme, main page :]

you need to check the "Demi Reminder Feature" - iirc the description is inaccurate and you should be using it. Try with that turned on and let me know if it works

**Comment by MarkusWo** [comment]
@k-kz It works! Thank You.

**Comment by k-kz** [comment]
@MarkusWo will get the descriptions fixed eventually, bugs first! o/
