### ISSUE TITLE
[AST] Lightspeed on 2min

### ISSUE THREAD

**Issue by dawn-star** [Nik-Potokar/XIVSlothCombo#652]
Lightspeed has a stupid recast of 90sec when it's actually required on 120s for double-weaving in buff windows

Currently the Lightspeed Feature will use Lightspeed whenever it's available, is there any way that it could be delayed until 120s?

Might be outside of the philosophical scope of the plugin, but AST needs as much button-bloat help as possible during the opener/2min burst :(

Thanks, as always!

![Astrodyne_timeline](https://user-images.githubusercontent.com/37399509/166940246-be55b4e0-10ca-4de7-962a-b7a54a7113d9.png)

**Comment by Taurenkey** [comment]
Whilst we have the means to do something like this, from experience it's something we would have to really think about how the end-user might interact with it. What I mean by that is although we _can_ try to line it up with optimal windows, we don't really have any ways to handle missed timing windows as it were. Right now we can get around some of those limitations by precrafting openers as it were, but for something like AST where you're looking to extend holding the CD through the fight instead of just at the start it would take some consideration. 

Our plugin may use a lot of logic but there's ultimately only so much we can do to "course correct" anything that gets done outwith constricted windows like this. For example, if the user manually activates Lightspeed in this scenario outwith a window, how do we treat the next window? Will Lightspeed even be off cooldown by then? 

We also consider the high-end raiding scene too when doing something like this, so even though on the surface it's an incredibly simple thing to hold onto a CD for a certain window, that's still a part of the skillset required to seperate average raiders from top-end clears. We're ultimately "Sloth Combo" and not "Savage Combo" so I'd say this is a feature request we'd have to put up for debate before considering.
