### ISSUE TITLE
[SAM] Kaeshi: Goken and Kaeshi: Setsugekka

### ISSUE THREAD

**Issue by Alkeyd** [Nik-Potokar/XIVSlothCombo#670]
I know there is an option to put Iaijutsu and its respective Kaeshi in the Single and AOE target combo, but would it be possible to create the option to put only Kaeshi in these combos?

**Comment by damolitionn** [comment]
Just curious if there's any particular reason? Also, I just want to double check if the option to have Tsubame on the same button as Iaijutusu isn't sufficient for this particular need?

**Comment by Alkeyd** [comment]
I use the Tsubame option on the same button as Iaijutusu, but sometimes I automatically after using the Iaijutusu I go back to the ST or AOE combo and miss the Tsubame window, I don't like to put the Iaijutusu in the combo, since he it has cast and it looks weird for me, but the option to turn on only Tsubame would be of great help and comfort. XD

**Comment by damolitionn** [comment]
For now, I won't implement the option to separate them in the ST and AOE. There's already options for Kaeshi on Iaijutsu so you can just hit your Iaijutsu button twice. I'm hesitant to add features to cater for every style of play unfortunately as that'll eventually lead to feature bloat. Not having Iaijutsu on ST because it looks weird and is a cast I think falls under that. Maybe in the future though, I'll add it.
