### ISSUE TITLE
[All Jobs] Suggestions for Physical Ranged and Raid Buffs

### ISSUE THREAD

**Issue by Megasder** [Nik-Potokar/XIVSlothCombo#711]
1. I have been leveling my rangeds and I found a problem with the simple interrupt feature, if a enemy is casting a normal spell (0,5 cast time) sometimes you waste your interrupt, so its posible to make that the feature only works on enemies that are casting a interrupt-able skill that are longer than 0,5 seconds (or more than 0,5 seconds left)? so you only use it on good skills instead of normal spells.

And maybe add the simple interrupt to tanks too

2. Second suggestion, for rangeds too, if you are out of combat and you don't have the Peloton buff replace anything (for example the main combo from simple feature) for Peloton, to ensure that you always have the buff. And if you want to hit something, make that it doesn't replace the skill if you have a enemy selected.

3. As for the all jobs suggestion, make that the raid group skills don't replace the main combo if you already have the buff from other party member, so they don't overlap, these skills would be:

- Astrologian - Divination
- Bard - Battle Voice | Radiant Finale
- Dancer - Technical Step
- Dragoon - Battle Litany
- Monk - Brotherhood
- Ninja - Mug
- Reaper - Arcane Circle
- Red Mage - Embolden
- Scholar - Chain Stratagem
- Summoner - Searing Light

Thank you for all your hard work with the plugin \o/

**Comment by k-kz** [comment]
1. This will only apply to users with high ping, as you can still successfully interrupt shorter casts with the feature when your ping is low or you're using a latency mitigation tool. We'll consider adding this in the future.

Also, the interrupt feature already exists for tanks.

2. Adding this would likely cause more problems than it would solve, in edge cases where you would use Peloton late on a pre-pull etc., So it's unlikely we'd add this. Consider just using Peloton manually. 

3. This level of optimisation only really "matters" at high-level play, at which point really the fix is to improve your party composition and not have to worry about this in the first place. Typically a large delay would just scuff rotations and lead to a net loss.

**Comment by Megasder** [comment]
Okey I understand, (as for the interrupt feature for tanks I meant if someday you guys make a "simple paladin" or other tank, it will automatically use interrupt like with the ranged simple features)
