### ISSUE TITLE
[SMN] Hold Bahamut / Phoenix Phase back to time for Searing Light

### ISSUE THREAD

**Issue by kryuzei** [Nik-Potokar/XIVSlothCombo#733]
My SMN had drifting issues because of my SPS and optimization that sometimes my searing light drift to mid burst phase (as in my bahamut / phoenix phase had gone off for 5-7 sec before my searing light on cd). Is it possible to have option to hold bahamut/phoneix phase until my searing phase is up?

**Comment by kryuzei** [comment]
nvm this, i misread how the sps friendly burst phase works :(

**Comment by Genesis-Nova** [comment]
Just for reference though, you *never* want to delay your demi summons for any reason its a huge dps loss and could possibly reduce the amount of demi summons you get in a fight.
Searing light and Demi summons will 100% eventually get out of sync due to spell speed. so that's just something SMNs have to live with if they have any spell speed at all.
