### ISSUE TITLE
[RPR] Communio Feature

### ISSUE THREAD

**Issue by MuttMeat** [Nik-Potokar/XIVSlothCombo#749]
I'm not sure if this was part of SlothCombo before the big cleanup, but, I'd like to request a feature that replaces **Gibbet/Gallows/Guillotine** with **Communio** when there's only 1 stack of **Shroud** left so it can't go to waste.

**Comment by MuttMeat** [comment]
There used to be, but it was removed a few updates back.

**Comment by damolitionn** [comment]
You mean this option?
![image](https://user-images.githubusercontent.com/87623949/170124614-0213883d-5bf7-4857-b277-733d5203b86d.png)

**Comment by Calvaire** [comment]
> You mean this option? ![image](https://user-images.githubusercontent.com/87623949/170124614-0213883d-5bf7-4857-b277-733d5203b86d.png)

Hi there, what i actually want is to replace Gibbet/Gallow with only Communio when just 1 orb left because I don't want Lemure's Slice to come in. So can it be an option?

**Comment by MuttMeat** [comment]
Little bit of a thread highjack there, but I think Calvaire's wish aligns pretty well with my own. It's really just a failsafe on Communio I'm personally looking for.

**Comment by damolitionn** [comment]
I could, is there any reason you don't want Lemure's Scythe to come in? Also if you do turn on that option and use Lemure's Scythe normally, Communio would replace Gibbet/Gallows/Guillotine at 1 stack of Shroud left anyway.

**Comment by Calvaire** [comment]
Maybe because I'm just fresh on RPR. Sometimes it's hard for me to remember which one(Cross/Void Reaping) is the enhanced version next if let Lemure's Slice replace. So I think only replace with Communio is better for me.
![Snipaste_2022-05-28_10-58-01](https://user-images.githubusercontent.com/4760425/170807259-b4c42a7c-ed7f-4b49-8603-c2a24cd17715.png)

**Comment by k-kz** [comment]
The Enshroud burst isn't positional or anything like that, and there's no logical reason to not use the free oGCD damage - I think if you're going to get Sloth to control your burst, it should execute all of the void/cross/lemures on one button as it currently does, rather than do fiddly bits and leave the end user open to more mistakes.

**Comment by Calvaire** [comment]
Actually I tried to put all enshroud combos in one buttion, but like i said, you only got 1.5s GCD so it's hard for me to exactly control the slot to weave oGCDs like **Arcane Circle, True North** or something else if pressing one button when at the same time you need to do mechanics. So it's why I choose to set different keys to these combos. 
Anyway, I'm not talking **'not use the free oGCD damage'** and it's convinent for me to arrange slots for oGCDs if not in one buttion. And all I ask is just a simple option that is a failsafe as MuttMeat said and for me it can save a key for Communio.
