### ISSUE TITLE
[All] Add option to put single button combo onto an action of your choice

### ISSUE THREAD

**Issue by MarcoMDF** [Nik-Potokar/XIVSlothCombo#787]
It would be useful (especially for streaming or recording purposes but also if you don't want to give up the ability to use your abilities manually) if you were able to specify the exact action you want to put your single-button combo on. SCombo would then put its rotations not on the first or third main GCD ability but on something like an emote. Jobs like RDM and SAM already give you the choice of what ability you want to put your combo on but letting you pick the exact action ID would be cool!

**Comment by k-kz** [comment]
We might expand the choice for job combo bases in the future, but it's unlikely we'll add actionID specification to any of them.

**Comment by Taurenkey** [comment]
To add onto what @k-kz has said, with Sloth being the scale it is, it would be difficult for us to truly have free choice over which action you can choose to override without potential issues. The basis of conflicting combos is due to features sharing a button to replace and is often done deliberately in line with design choices. So whilst I won't guarantee anything, if we do implement anything then it will be on just _some_ features and even then, we may limit which action it can replace. The most likely candidates will be the "1-2-3" combo features being candidates for replacing any of those steps, but outwith that, major consideration required.

**Comment by NikkoXIV** [comment]
> Jobs like RDM and SAM already give you the choice of what ability you want to put your combo on but letting you pick the exact action ID would be cool!

Only reason I could get away with doing it on RDM was that I wrote it from the ground up with that intention, and I have to be more thoughtful when adding new features that I don't break anything and where I can put the feature so it will work.  It wouldn't be bad to choose what action in a 1-2-3 combo to use and that could be done fairly easily.
