### ISSUE TITLE
[MCH] Fix Drill feature to not go off when Reassemble has < 7 seconds on its cooldown

### ISSUE THREAD

**Issue by Iaotle** [Nik-Potokar/XIVSlothCombo#83]
Maybe even higher, but 7 should be enough.

**Comment by Codemned** [comment]
Main, Alternate or both?

**Comment by Iaotle** [comment]
Drill should never go up on main combo if you have that timer remaining.

**Comment by Iaotle** [comment]
So both I guess?

**Comment by sauronshotdogs** [comment]
Press sure drill is supposed to go off on main, as you should only use reassemble for the 2 ogcd that generate power. Please don't change main combo

**Comment by Iaotle** [comment]
It's literally not? Reassemble has a 55 second cooldown which means it has to drift in order to use it on drill. This means drill has to be delayed until it's up sometimes.

**Comment by Codemned** [comment]
I've added this to Alternate drill on main.
If Reasemble is about to come off cooldown Drill will not be used. All this really does is make sure that If reasemble comes off cooldown you don't need to check if you have a decent spender off cooldown (Drill will always be available).

As opposed to how it was prior where Reasemble could come off cooldown and you'd trigger it too early and have nothing worthy to spend it on because you didn't check before hand....

Hope this is satisfactory.

**Comment by Codemned** [comment]
After further testing I've noticed that this change doesn't line up consistenly across different levels and I'll be reverting it to the way it was previously. You'll just have to hold Reasemble for a few seconds for Drill to come off cooldown for the time being.

**Comment by Iaotle** [comment]
@Codemned I'm holding drill for a few seconds (almost 10) and it interrupts my main combo, so it's a pretty big issue. I would just fix the checks for drill with an extra level check and Reassemble CD check. Not sure what the inconsistency is. I can do it myself later when I get time.

**Comment by Codemned** [comment]
Don't hold drill, hold Reasemble.

**Comment by Iaotle** [comment]
Why would I hold reassemble for like 18 seconds tho?

**Comment by Codemned** [comment]
5~ seconds but I'm done with this issue create a new MCH feature that fills your very niche needs.

**Comment by Iaotle** [comment]
@Codemned you should be nicer dude. I can implement it myself no problem, but you shouldn't talk like that. This whole plugin is full of niche features and this one happens to be a really easy and useful one for machinist.

**Comment by damolitionn** [comment]
I feel like this whole premise is flawed. If you're Reassembling on CD below level 90 content where Drill is the only option for Reassemble, Reassemble will always be off CD 5 seconds before Drill (Drill coming off CD every 20 seconds, vs Reassemble on CD coming off every 55 seconds). So if you were playing optimally and using Drill on CD and Reassemble on CD which IMO isn't super difficult when you have the plugin or understood at least how the synergy works you'll only ever have to wait 5 seconds for a Reassembled Drill. Even on the Balance, they advocate to drift Reassemble. I feel like this is just a flawed misunderstanding of the class which is symptomatic of some of the feature choices in other classes too.

**Comment by Iaotle** [comment]
Yeah this is assuming full uptime though... Which is not at all how it works out in reality. Why drift a cooldown for 15 seconds when you can drift it for 5?

If my drill is coming off cooldown 5 seconds before reassemble, then I have another 15 seconds of drift for reassemble after using drill early. To me it seems like holding drill for 5 seconds is the correct choice in that scenario.

**Comment by damolitionn** [comment]
Balance discord: https://discord.com/invite/thebalanceffxiv

Firstly, I don't think I've been in a situation where I've let Drill drift that much, most Ex/Savage fights are at least nice about 1 min CDs and if they're not you might as well just hold off on everything during forced downtime anyway and it'll drift back to normal. 

Secondly, I wouldn't even hold Drill in that scenario. Like @Codemned said earlier, hold reassemble not drill. Drill comes off CD more often than Reassemble and the latter only guarantees that it crits. So in that situation, I'd just pop Drill as often as possible and just get Reassemble off the next available Drill. Again, a situation like that is already bad rotation wise so you're stuck with adapting, seeing as Drill's drifted which means it's probably not capturing raid buffs. So, raid buffs + Reassembled Drill isn't a benefit you're gaining in this scenario anyway.

Finally, it's also sub level 90 content. Which means this feature falls into two categories:
1. You're doing Ultimates and, for some reason, your Drills are drifting really far out and you want this feature to fix your sub optimal game play. Which, again wouldn't make sense as more Drills is a bigger gain than holding Drill for Reassemble. 
2. You're doing roulettes and levelling. At which does it even matter if you're drifting a CD because that's just the nature of dungeons.

So, all up is the feature even worth it because the moment you hit 84 and Reassemble becomes charges it's a whole different ball game mechanically.

**Comment by Iaotle** [comment]
I wanted a link to MCH drift discussion I know about balance discord.

Anyway I talked to some people in balance discord and they pretty much explained the same thing you did @damolitionn .
It just could have been explained better in the first place and there wouldn't be a discussion.
