### ISSUE TITLE
[WHM] Level sync Medica II to Medica

### ISSUE THREAD

**Issue by priprii** [Nik-Potokar/XIVSlothCombo#904]
Medica II requires Lv50, so it should switch to Medica when below Lv50, similar to how Cure II switches to Cure I below Lv30.

I assume the "Medica Feature" does do this, but I think there should also be separate option for doing it for people who don't want the additional feature of replacing Medica II with Medica when the regen effect is already active.

**Comment by cupcake121** [comment]
I'm curious why you don't want to replace Medica II when the regen effect is active.

Medica I has 400 potency. Under level 85 it's 300 potency.
Medica II has 250 potency+150 HoT potency (which ticks 5 times for a total of 750 potency HoT) Under level 85 Medica II has 200 potency and 100 HoT potency.

Here are the potencies visualized in the order they get applied.

Medica 2 followed by Medica 2 = 250 + 150 + 250 + 150 + 150 +150 +150 + 150 (18 seconds) 
You get an extra tick by refreshing the buff with your 2nd Medica 2

Medica 2 followed by Medica 1 = 250 + 150 + 400 + 150 + 150 + 150 +150 (15 seconds)


If you're in a scanario that requires you to cast 2 aoe heals (and you're out of lilies) it's fair to assume you want as much potency as soon as possible which is why Medica II into Medica I is used, it's the more burst~y variant.

**Comment by k-kz** [comment]
Based on what @cupcake121 has outlined above, I think it's fair to say we can close this for now.

@priprii let us know if you think we've missed something!
