### ISSUE TITLE
[MCH] Why is MachinistAlternateMainCombo only putting Hotshot/Anchor on Reassemble cooldown?

### ISSUE THREAD

**Issue by Iaotle** [Nik-Potokar/XIVSlothCombo#94]
I understand why drill is connected to reassemble, but shouldn't the other cooldowns just be used as often as possible? Can someone clarify?

**Comment by Iaotle** [comment]
https://github.com/Nik-Potokar/XIVSlothCombo/pull/95

**Comment by damolitionn** [comment]
At level 90, Chainsaw/Air Anchor/Drill can all be used with Reassemble because of the charge system of Reassemble and all 3 skills have the same potency so it's mostly just about timing of when things go off. 

Ideally, you want to Reassemble on Chainsaw after the opener as it's also a min CD. So, on the general raid opener you'd Reassemble Air Anchor in the beginning and Reassemble Chainsaw before your WF window. On the Heavy Buff Opener you'd Reassemble Air Anchor and Reassemble Chainsaw back to back before your WF window. After the opener, you'll want to save your Reassembles for only Chainsaw every minute. Due to the charge system, you'll no longer have drift because what you'll want to do is when the first charge of Reassemble comes off CD you'll hold it for 30 seconds to use with Chainsaw, and then the next charge will be ready 30 seconds after that. 

So really, at level 90 you'd actually unlink Drill from Reassemble and have it timed with Chainsaw.

Here's an example of someone going through the rotation for 4 mins: https://www.youtube.com/watch?v=uUoS9aiWxcs
