### ISSUE TITLE
[DNC] Option to prevent standard step during technical window

### ISSUE THREAD

**Issue by Hikarichan** [Nik-Potokar/XIVSlothCombo#943]
Was wondering if it was possible to have an option to make it so when you have the technical buff up to disable the use of standard step
until it has worn off. 
been a few times where standard step lines up just right where it will go off after technical goes off and its not very ideal

just a thought 
thank you for the amazing addon its amazing

**Comment by k-kz** [comment]
Are you asking for this inside of full-blown simple mode?

Unless I've missed something in recent patches, I'm pretty sure it's still optimal for SS to be used inside of the TS/Devilment burst, assuming the whole dance+finish is executed under the buffs. Let me know if I'm mistaken! 👍

**Comment by Hikarichan** [comment]
hmm 
yeah its in the simple mode
i know in the opener with no access to fan dances and saber dances its optimal to do SS in the buff window
but during a non opener buff window when u have fan dances and saber dances saved up im pretty sure the optimal rotation would be to dump saber dances with weaving fan dances over a ss 

is it possible to make a toggle to prioritize those over ss during tech/dev 
cuz it seems like as soon as i fire off tech sometimes it goes straight to ss 
maybe im wrong but just figured id bring up as an option 

thank you for the quick response :)

**Comment by k-kz** [comment]
You should be fine dumping all of your Feathers, Esprit and so on during your burst, even using SS at the beginning - that being said, the priority order isn't quite correct for SS so that'll get sorted soon - there should be no need for an option to accommodate as it will just be further optimised.

We've got a lot to chew through for [3.0.17.1](https://github.com/Nik-Potokar/XIVSlothCombo/milestone/3), but if it doesn't make it in, it'll be done by 3.0.17.2.

**Comment by Hikarichan** [comment]
ok sounds good! i was just noticing ss being a lil off during the bust window is only reason i asked about a toggle but you answered that! 
thank you so much! the dnc combo is pretty spot on otherwise :)

**Comment by Valmere** [comment]
The top 3 parses from NA dancers on p5s show a higher priority on dumping saber dances and fans over using SS during tech step windows (past the opening one)

https://www.fflogs.com/reports/1M8X6tTkcxagG2pF#fight=56&type=casts&source=567&view=events
https://www.fflogs.com/reports/WLwpXh9rRnBcAybj#fight=4&type=casts&source=13&view=events
https://www.fflogs.com/reports/DF46VmHr7RhpY2QB#fight=52&type=casts&source=61&view=events

**Comment by k-kz** [comment]
@Hikarichan @Valmere This has been addressed and is currently in testing (I've been busy irl, sorry for the wait!) - instead of including an option to completely prevent `Standard Step` use during `Technical Step`, I've instead sorted out the priorities of everything and introduced certain restrictions, to prevent the use of `Standard Step` from potential `Technical Step` drift, while also ensuring `Devilment` and `Flourish` are getting used at the right times.

You can check out a detailed changelog of what's coming soon for DNC [here](https://github.com/Nik-Potokar/XIVSlothCombo/pull/1058). It'll be in the next release! :]
