### ISSUE TITLE
[WAR]

### ISSUE THREAD

**Issue by Celesmeh** [Nik-Potokar/XIVSlothCombo#950]
Does not use inner release stacks before adding infuriate to combo.  Pic Attached 
![image](https://user-images.githubusercontent.com/60585813/187088890-68669bff-1fa5-4967-ad66-1465103fda87.png)
![image](https://user-images.githubusercontent.com/60585813/187088901-9501d91e-f13e-4907-a437-c8e659741f38.png)

**Comment by damolitionn** [comment]
If you're talking about the Main Combo, since 6.1 Inner Release only affects Fell Cleave and Decimate so the order of skill usage has changed since then. Before then, you would Inner Release and use Fell Cleave and then after the stacks are spent, you would use Infuriate so that you wouldn't lose Inner Chaos to Inner Release.

After 6.1, Infuriate and Inner Release no longer share that interaction, so there's no longer an issue of having Infuriate and Inner Release up at the same time. So you're able to use 3 Fell Cleaves from Inner Release and an Inner Chaos from Infuriate.

Here's an example of how they interact:
![image](https://user-images.githubusercontent.com/87623949/187096897-86c7726e-6eb1-4616-9505-5d4f9a812930.png)
