### ISSUE TITLE
[BLM] Not using Sharpcast/Triplecast except when at 2 stacks

### ISSUE THREAD

**Issue by Ariao4583** [Nik-Potokar/XIVSlothCombo#954]
During the opener, sharpcast/triplecast is used fine (once each), but then refuses to use it again until it hits 2 stacks on either.  Can not use manually either.

Debug file attached below

If just me being dumb please roast ♥

```
START DEBUG LOG

Plugin Version: 3.0.17.1

Current Job: black mage / Black Mage / BLM
Current Job Index: 7

Current Zone: 960
Current Party Size: 2

START ENABLED FEATURES
2001 - BLM_Mana
2002 - BLM_LeyLines
2006 - BLM_Thunder
2008 - BLM_AoE_SimpleMode
2011 - BLM_ThunderUptime
2013 - BLM_Simple_Buffs
2014 - BLM_Simple_Buffs_LeyLines
2015 - BLM_Simple_Casts
2016 - BLM_Simple_Casts_Pooling
2017 - BLM_Simple_XenoPooling
2018 - BLM_Simple_Opener
2019 - BLM_Simple_OpenerAlternate
2020 - BLM_AoE_Simple_Foul
2021 - BLM_Simple_Transpose
2022 - BLM_Simple_Transpose_Pooling
2024 - BLM_Simple_Transpose_LeyLines
2027 - BLM_Simple_CastMovement_Xeno
2028 - BLM_Simple_CastMovement_Scathe
2029 - BLM_TransposeThunder
2030 - BLM_TransposeThunderUptime
80090 - BLMPvP_BurstMode
80091 - BLMPvP_BurstMode_NightWing
90000 - PvP_EmergencyHeals
90001 - PvP_EmergencyGuard
90002 - PvP_QuickPurify
90003 - PvP_MashCancel
100000 - ALL_Tank_Interrupt
100001 - ALL_Tank_Reprisal
100020 - ALL_Caster_Addle
100030 - ALL_Melee_Feint
100031 - ALL_Melee_TrueNorth
100040 - ALL_Ranged_Mitigation
100095 - ALL_Ranged_Menu
100096 - ALL_Melee_Menu
100097 - ALL_Caster_Menu
100099 - ALL_Tank_Menu
END ENABLED FEATURES

Redundant IDs found: 0
Status Effect Count: 0
START STATUS EFFECTS
END STATUS EFFECTS
END DEBUG LOG
```

**Comment by k-kz** [comment]
Note: Ignore `Plugin Version: 3.0.17.1` - @Ariao4583 is a beta tester and running the officially distributed beta.

**Comment by GibXIV** [comment]
Ran trough a dummy test with my own settings, and your settings based on your debug log on the now release 3.0.17.1

with your settings indeed it only uses swiftcast when it has 2 stacks, but that is because you have enabled the pool triplecast option:
![image](https://user-images.githubusercontent.com/105976933/187493998-be77cddf-ee6f-47fa-9a42-dc87a9874dac.png)
When i uncheck the pool option it will use up swift and triplecast whenever available.

sharpcast is being used for me with your settings, but it only uses it whenever it needs a proc, if it already has thunder/fire proc active, or enough time left before its needed and can proc naturally, it won't activate it till needed.

please try again on release build with pool option off, or let me know if i am misinterpreting this.

**Comment by Ariao4583** [comment]
Did more testing, it seems the icon will pop up for surecast but not use it due to not needing to use it, which confused me. 

For triple cast, I should clarify, I am unable to use it -manually- at all unless it is sitting at 2 stacks, negating the purpose of pooling it

**Comment by Ariao4583** [comment]
Fixed: Local error, wiped all settings for XIVSlothCombo entirely (deleting files, not just turning off), working fine after doing so ♥
