### ISSUE TITLE
[NIN] Add "Only Outside of Trick Attack" sub-option to "Hold one charge" Ninjutsu feature.

### ISSUE THREAD

**Issue by ArcanaXVIII** [Nik-Potokar/XIVSlothCombo#962]
Hello everyone,

Just an enhancement suggestion for NIN after talking about it with a few people over on Discord.

Currently, Sloth either use one Raiton during filler or you can use the "Hold one charge" option to manually use that pooled charge to have a second Raiton during Trick Attack as is optimal.

Would it be possible to add a sub-option to "Hold one charge" so that it only holds it outside of burst and still be able to use all charges during Trick Attack?

We are looking for the behavior displayed in this video :
https://streamable.com/uk7z3s

Thanks!

**Comment by Mentholman112** [comment]
I think "Hold one charge" also stops Suiton being cast if you only have one mudra charge as well.

 If you've set Suiton to prep cast within the 0-15 Trick attack CD window I think it'd be more efficient if the "Hold one charge" rule didn't apply to Suiton. So sloth will still cast Suiton when its at 1 Mudra charge with another close to coming up instead of ignoring the 0-15 rule and waiting until you're fully capping at 2 charges?

**Comment by Rollo1h** [comment]
Hello.
I agree with the NINJA enhancement proposal above.
I think the same behavior could be achieved by adding a sub option in "#342 Use Raiton only during TrickAttack debuff".

**Comment by k-kz** [comment]
Addressed in #978
