### ISSUE TITLE
Import and Export Settings

### ISSUE THREAD

**Issue by Kazarann** [Nik-Potokar/XIVSlothCombo#988]
Hey, Most people only play a few jobs and ive been wanting to try out some other jobs a little however knowing what settings to use without knowing the job in-depth does not make it easy. Ive had a few people share settings but have had to do it by hand.

Import/Export setting from/to clipboard button under dropdown for each job and a global import for all setting maybe

**Comment by k-kz** [comment]
It's unlikely we'll implement this for a few reasons - primarily because feature/option choice can vary depending on the user's hotbar layout, skill speed and so on.

We also recommend getting to know a given job in a standard capacity before using Sloth to change the way things work. This way, you can naturally apply settings as you go and get a comfortable setup and playstyle that suits you without sabotaging your understanding of the job and thus your/other players' game experience.
